#!/usr/bin/env bash
# Copyright (C) 2025 spur27
# SPDX-License-Identifier: BSL-1.0
#
# This file is part of RenWeb Engine.
#
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# =============================================================================
# build_all_archs.sh - Build RenWeb for all supported architectures
# =============================================================================
# This script builds the RenWeb executable for all supported architectures
# based on the detected operating system and available cross-compilers.
#
# Usage:
#   ./build_all_archs.sh [--bundle]
#
# Options:
#   --bundle    Bundle runtime libraries for portable deployment
# =============================================================================

set -e

# =============================================================================
# Configuration
# =============================================================================

ENABLE_BUNDLE=false

# Color codes for output
RESET='\033[0m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
BOLD='\033[1m'

# =============================================================================
# Supported Toolchains and Architectures
# =============================================================================

# Linux toolchains (simple list - bash 3.2 compatible)
LINUX_TOOLCHAINS="x86_64-linux-gnu i686-linux-gnu aarch64-linux-gnu arm-linux-gnueabihf mips-linux-gnu mipsel-linux-gnu mips64-linux-gnuabi64 mips64el-linux-gnuabi64 powerpc-linux-gnu powerpc64-linux-gnu riscv64-linux-gnu s390x-linux-gnu sparc64-linux-gnu"

MACOS_ARCHITECTURES="arm64 x86_64"
WINDOWS_ARCHITECTURES="x64 x86 arm64 arm"

# =============================================================================
# Helper Functions
# =============================================================================

print_header() {
    echo -e "${CYAN}${BOLD}========================================${RESET}"
    echo -e "${CYAN}${BOLD}$1${RESET}"
    echo -e "${CYAN}${BOLD}========================================${RESET}"
}

print_info() {
    echo -e "${GREEN}${BOLD}[INFO]${RESET} $1"
}

print_warning() {
    echo -e "${YELLOW}${BOLD}[WARN]${RESET} $1"
}

print_error() {
    echo -e "${RED}${BOLD}[ERROR]${RESET} $1"
}

print_success() {
    echo -e "${GREEN}${BOLD}[SUCCESS]${RESET} $1"
}

print_building() {
    echo -e "${MAGENTA}${BOLD}[BUILD]${RESET} Building for ${CYAN}$1${RESET} (${YELLOW}$2${RESET})"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

toolchain_exists() {
    command_exists "$1-gcc" && command_exists "$1-g++"
}

build_for_toolchain() {
    local toolchain=$1
    local arch_name=$2
    
    print_building "$arch_name" "$toolchain"
    
    local bundle_flag=""
    if [ "$ENABLE_BUNDLE" = true ]; then
        bundle_flag="BUNDLE=true"
    fi
    
    if make clear TOOLCHAIN="$toolchain" TARGET=release; then
        if make TOOLCHAIN="$toolchain" TARGET=release $bundle_flag -j$(nproc 2>/dev/null || echo 4); then
            print_success "Built for $arch_name successfully"
            return 0
        else
            print_error "Failed to build for $arch_name"
            return 1
        fi
    else
        print_error "Failed to clear for $arch_name"
        return 1
    fi
}

build_native() {
    local arch_name=$1
    
    print_building "$arch_name" "native"
    
    local bundle_flag=""
    if [ "$ENABLE_BUNDLE" = true ]; then
        bundle_flag="BUNDLE=true"
    fi
    
    if make clear TARGET=release; then
        if make TARGET=release $bundle_flag -j$(nproc 2>/dev/null || echo 4); then
            print_success "Built native for $arch_name successfully"
            return 0
        else
            print_error "Failed to build native"
            return 1
        fi
    else
        print_error "Failed to clear native build"
        return 1
    fi
}

# =============================================================================
# Detect Operating System and Architecture
# =============================================================================

detect_os() {
    case "$(uname -s)" in
        Linux*)
            OS_NAME="Linux"
            HOST_ARCH=$(uname -m)
            ;;
        Darwin*)
            OS_NAME="macOS"
            HOST_ARCH=$(uname -m)
            ;;
        CYGWIN*|MINGW*|MSYS*)
            OS_NAME="Windows"
            if [ -n "$VSCMD_ARG_TGT_ARCH" ]; then
                HOST_ARCH="$VSCMD_ARG_TGT_ARCH"
            elif [ -n "$PROCESSOR_ARCHITECTURE" ]; then
                case "$PROCESSOR_ARCHITECTURE" in
                    AMD64) HOST_ARCH="x86_64" ;;
                    x86) HOST_ARCH="x86" ;;
                    ARM64) HOST_ARCH="arm64" ;;
                    *) HOST_ARCH="$PROCESSOR_ARCHITECTURE" ;;
                esac
            else
                HOST_ARCH="x86_64"
            fi
            ;;
        *)
            print_error "Unknown operating system: $(uname -s)"
            exit 1
            ;;
    esac
}

# =============================================================================
# Build Functions by OS
# =============================================================================

build_linux() {
    local success_count=0
    local fail_count=0
    local total_count=0
    
    print_header "Building for Linux - All Architectures (13 total)"
    print_info "Host architecture: $HOST_ARCH"
    if [ "$ENABLE_BUNDLE" = true ]; then
        print_info "Bundling enabled: Libraries will be bundled with each build"
    fi
    echo ""
    
    # Map host architecture to toolchain name to skip it later
    local host_toolchain=""
    case "$HOST_ARCH" in
        x86_64) host_toolchain="x86_64-linux-gnu" ;;
        i686|i386) host_toolchain="i686-linux-gnu" ;;
        aarch64|arm64) host_toolchain="aarch64-linux-gnu" ;;
        armv7l|armhf) host_toolchain="arm-linux-gnueabihf" ;;
        mips) host_toolchain="mips-linux-gnu" ;;
        mipsel) host_toolchain="mipsel-linux-gnu" ;;
        mips64) host_toolchain="mips64-linux-gnuabi64" ;;
        mips64el) host_toolchain="mips64el-linux-gnuabi64" ;;
        ppc) host_toolchain="powerpc-linux-gnu" ;;
        ppc64) host_toolchain="powerpc64-linux-gnu" ;;
        riscv64) host_toolchain="riscv64-linux-gnu" ;;
        s390x) host_toolchain="s390x-linux-gnu" ;;
        sparc64) host_toolchain="sparc64-linux-gnu" ;;
    esac
    
    print_info "Building native (host architecture: $HOST_ARCH)..."
    total_count=$((total_count + 1))
    if build_native "native ($HOST_ARCH)"; then
        success_count=$((success_count + 1))
    else
        fail_count=$((fail_count + 1))
    fi
    echo ""
    
    for toolchain in $LINUX_TOOLCHAINS; do
        if [ "$toolchain" = "$host_toolchain" ]; then
            print_info "Skipping $toolchain (already built natively)"
            continue
        fi
        
        total_count=$((total_count + 1))
        
        if toolchain_exists "$toolchain"; then
            if build_for_toolchain "$toolchain" "$toolchain"; then
                success_count=$((success_count + 1))
            else
                fail_count=$((fail_count + 1))
            fi
        else
            print_warning "Toolchain $toolchain not found, skipping"
            fail_count=$((fail_count + 1))
        fi
        echo ""
    done
    
    print_header "Build Summary"
    echo -e "${GREEN}Successful builds: ${BOLD}$success_count${RESET}"
    echo -e "${RED}Failed builds: ${BOLD}$fail_count${RESET}"
    echo -e "${CYAN}Total attempts: ${BOLD}$total_count${RESET}"
    
    if [ $success_count -gt 0 ]; then
        print_info "Built executables are located in: ./build/"
        ls -lh ./build/ 2>/dev/null | grep -E "renweb-.*-linux-" || true
    fi
}

build_macos() {
    local success_count=0
    local fail_count=0
    local total_count=0
    
    print_header "Building for macOS - Multiple Architectures"
    print_info "Host architecture: $HOST_ARCH"
    if [ "$ENABLE_BUNDLE" = true ]; then
        print_info "Bundling enabled: Libraries will be bundled with each build"
    fi
    echo ""
    
    if ! command_exists "clang++"; then
        print_error "clang++ not found!"
        return 1
    fi
    
    # Check if Xcode Command Line Tools are installed
    if ! xcode-select -p >/dev/null 2>&1; then
        print_error "Xcode Command Line Tools not installed!"
        print_info "Installing Xcode Command Line Tools..."
        if xcode-select --install 2>&1; then
            print_info "Please wait for installation to complete, then run this script again"
            return 1
        fi
    fi
    
    local ncpu=$(sysctl -n hw.ncpu 2>/dev/null || echo 4)
    
    local SUPPORTED_ARCHS="arm64 x86_64"
    
    print_info "Supported architectures: $SUPPORTED_ARCHS"
    print_info "Note: macOS cross-compilation uses -arch flag with Xcode SDK"
    echo ""
    
    for arch in $SUPPORTED_ARCHS; do
        total_count=$((total_count + 1))
        
        print_building "$arch" "clang++ -arch $arch"
        
        make clear >/dev/null 2>&1
        
        local bundle_flag=""
        if [ "$ENABLE_BUNDLE" = true ]; then
            bundle_flag="BUNDLE=true"
        fi
        
        if ARCH="$arch" ARCH_FLAGS="-arch $arch" make TARGET=release $bundle_flag -j$ncpu 2>&1; then
            print_success "Built for $arch successfully"
            success_count=$((success_count + 1))
        else
            print_error "Failed to build for $arch"
            fail_count=$((fail_count + 1))
        fi
        echo ""
    done
    
    if [ $success_count -eq 2 ]; then
        print_info "Creating universal binary (arm64 + x86_64)..."
        
        local arm64_bin=$(ls ./build/renweb-*-macos-arm64 2>/dev/null | head -1)
        local x86_64_bin=$(ls ./build/renweb-*-macos-x86_64 2>/dev/null | head -1)
        
        if [ -n "$arm64_bin" ] && [ -n "$x86_64_bin" ]; then
            local version=$(grep -o '"version"[^"]*"[^"]*"' info.json | cut -d'"' -f4)
            local universal_bin="./build/renweb-${version}-macos-universal"
            
            if lipo -create "$arm64_bin" "$x86_64_bin" -output "$universal_bin" 2>/dev/null; then
                print_success "Universal binary created: $universal_bin"
                success_count=$((success_count + 1))
                
                print_info "Universal binary architectures:"
                lipo -info "$universal_bin"
            else
                print_warning "Could not create universal binary (lipo failed)"
            fi
        else
            print_warning "Could not find both architecture binaries to create universal binary"
        fi
    fi
    
    print_header "Build Summary"
    echo -e "${GREEN}Successful builds: ${BOLD}$success_count${RESET}"
    echo -e "${RED}Failed builds: ${BOLD}$fail_count${RESET}"
    echo -e "${CYAN}Total attempts: ${BOLD}$total_count${RESET}"
    
    if [ $success_count -gt 0 ]; then
        print_info "Built executables are located in: ./build/"
        ls -lh ./build/ 2>/dev/null | grep -E "renweb-.*-macos-" || true
    fi
}

build_windows() {
    local success_count=0
    local fail_count=0
    local total_count=3
    
    print_header "Building for Windows - All Architectures (3 total)"
    print_info "Detected Windows environment"
    echo ""
    
    local vswhere="/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
    if [ ! -f "$vswhere" ]; then
        vswhere="/c/Program Files/Microsoft Visual Studio/Installer/vswhere.exe"
    fi
    
    local vs_path=""
    if [ -f "$vswhere" ]; then
        vs_path=$("$vswhere" -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>/dev/null | head -1)
    fi
    
    if [ -z "$vs_path" ]; then
        if [ -d "/c/Program Files/Microsoft Visual Studio/2022/Community" ]; then
            vs_path="/c/Program Files/Microsoft Visual Studio/2022/Community"
        elif [ -d "/c/Program Files/Microsoft Visual Studio/2022/Professional" ]; then
            vs_path="/c/Program Files/Microsoft Visual Studio/2022/Professional"
        fi
    fi
    
    if [ -z "$vs_path" ]; then
        print_error "Could not find Visual Studio installation"
        print_info "Please install Visual Studio 2022 with C++ tools"
        return 1
    fi
    
    print_info "Visual Studio: $vs_path"
    
    local vcvars_path="$vs_path/VC/Auxiliary/Build"
    if [ ! -d "$vcvars_path" ]; then
        print_error "Could not find vcvars at: $vcvars_path"
        return 1
    fi
    
    local architectures="x64:x86_64:vcvars64.bat x86:x86_32:vcvars32.bat arm64:arm64:vcvarsamd64_arm64.bat"
    
    for arch_spec in $architectures; do
        IFS=':' read -r win_arch make_arch vcvars <<< "$arch_spec"
        
        echo ""
        print_building "$win_arch" "$vcvars"
        
        # Convert paths for Windows cmd
        local vcvars_win=$(cygpath -w "$vcvars_path/$vcvars" 2>/dev/null || echo "$vcvars_path\\$vcvars")
        
        local temp_bat=$(mktemp --suffix=.bat)
        cat > "$temp_bat" <<EOF
@echo off
call "$vcvars_win" >nul 2>&1
if errorlevel 1 exit /b 1
make clear ARCH=$make_arch TARGET=release >nul 2>&1
if errorlevel 1 exit /b 1
make ARCH=$make_arch TARGET=release -j4
EOF
        
        if cmd //c "$(cygpath -w "$temp_bat" 2>/dev/null || echo "$temp_bat")" 2>&1; then
            print_success "Built $win_arch successfully"
            success_count=$((success_count + 1))
        else
            print_error "Build failed for $win_arch"
            fail_count=$((fail_count + 1))
        fi
        
        rm -f "$temp_bat"
    done
    
    echo ""
    print_header "Build Summary"
    echo -e "${GREEN}Successful builds: ${BOLD}$success_count${RESET}"
    echo -e "${RED}Failed builds: ${BOLD}$fail_count${RESET}"
    echo -e "${CYAN}Total attempts: ${BOLD}$total_count${RESET}"
    
    if [ $success_count -gt 0 ]; then
        print_info "Built executables are located in: ./build/"
        ls -lh ./build/ 2>/dev/null | grep -E "renweb-.*-windows-" || true
    fi
    
    if [ $fail_count -gt 0 ]; then
        print_warning "Failed builds may be due to missing toolchains"
        print_info "Install via Visual Studio Installer: MSVC v143 ARM64 build tools"
    fi
}

# =============================================================================
# Main Script
# =============================================================================

main() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --bundle)
                ENABLE_BUNDLE=true
                shift
                ;;
            --help|-h)
                echo "Usage: $0 [--bundle]"
                echo ""
                echo "Description:"
                echo "  Automatically detects your operating system and builds release"
                echo "  versions for all supported architectures on that platform."
                echo ""
                echo "Options:"
                echo "  --bundle    Bundle runtime libraries for portable deployment"
                echo ""
                echo "Supported platforms:"
                echo "  - Linux:   13 architectures"
                echo "             x86_64, x86_32, arm64, arm32, mips32, mips32el, mips64,"
                echo "             mips64el, powerpc32, powerpc64, riscv64, s390x, sparc64"
                echo "  - macOS:   2 architectures (x86_64, arm64)"
                echo "  - Windows: 3 architectures (x86_64, x86_32, arm64)"
                echo ""
                echo "Example:"
                echo "  $0            # Build all architectures for current OS"
                echo "  $0 --bundle   # Build with bundled libraries for portability"
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done
    
    detect_os
    
    print_header "RenWeb Multi-Architecture Build Script"
    print_info "Detected OS: $OS_NAME"
    print_info "Host architecture: $HOST_ARCH"
    echo ""
    
    # Check if make is available (not needed for Windows batch file approach)
    if [ "$OS_NAME" != "Windows" ] && ! command_exists make; then
        print_error "make command not found. Please install make."
        exit 1
    fi

    if ! make clean; then
        print_error "Failed to clean previous builds."
        exit 1
    fi
    
    case "$OS_NAME" in
        Linux)
            build_linux
            ;;
        macOS)
            build_macos
            ;;
        Windows)
            build_windows
            ;;
        *)
            print_error "Unsupported operating system: $OS_NAME"
            exit 1
            ;;
    esac
}

main "$@"
