# Copyright (C) 2025 spur27
# SPDX-License-Identifier: BSL-1.0
#
# This file is part of RenWeb Engine.
#
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# -----------------------------------------------------------------------------
# Toolchain prefix - Supported Linux cross-compilers
# -		ARM 32-bit (Linux):          TOOLCHAIN := arm-linux-gnueabihf
# -		ARM 64-bit (Linux):          TOOLCHAIN := aarch64-linux-gnu
# -		MIPS 32-bit BE (Linux):      TOOLCHAIN := mips-linux-gnu
# -		MIPS 32-bit LE (Linux):      TOOLCHAIN := mipsel-linux-gnu
# -		MIPS 64-bit BE (Linux):      TOOLCHAIN := mips64-linux-gnuabi64
# -		MIPS 64-bit LE (Linux):      TOOLCHAIN := mips64el-linux-gnuabi64
# -		PowerPC 32-bit (Linux):      TOOLCHAIN := powerpc-linux-gnu
# -		PowerPC 64-bit (Linux):      TOOLCHAIN := powerpc64-linux-gnu
# -		RISC-V 64-bit (Linux):       TOOLCHAIN := riscv64-linux-gnu
# -		S390x (Linux):               TOOLCHAIN := s390x-linux-gnu
# -		SPARC 64-bit (Linux):        TOOLCHAIN := sparc64-linux-gnu
# -		x86_64 (Linux):              TOOLCHAIN := x86_64-linux-gnu (or native)
# -		x86 32-bit (Linux):          TOOLCHAIN := i686-linux-gnu
# -		x86 32-bit (macOS):          Use clang with -m32 flag (no TOOLCHAIN)
# -		Windows (cl.exe):            No TOOLCHAIN - use native cl.exe compiler
# -		macOS (clang):               No TOOLCHAIN - use native clang compiler
# -----------------------------------------------------------------------------
TOOLCHAIN :=
ifdef TOOLCHAIN
	CROSS_COMPILE := $(TOOLCHAIN)-
	SYSROOT := --sysroot=/usr/$(TOOLCHAIN)
	# Set ARCH based on TOOLCHAIN
	ifeq ($(TOOLCHAIN),arm-linux-gnueabihf)
		ARCH := arm32
	else ifeq ($(TOOLCHAIN),aarch64-linux-gnu)
		ARCH := arm64
	else ifeq ($(TOOLCHAIN),i686-linux-gnu)
		ARCH := x86_32
	else ifeq ($(TOOLCHAIN),mips-linux-gnu)
		ARCH := mips32
	else ifeq ($(TOOLCHAIN),mipsel-linux-gnu)
		ARCH := mips32el
	else ifeq ($(TOOLCHAIN),mips64-linux-gnuabi64)
		ARCH := mips64
	else ifeq ($(TOOLCHAIN),mips64el-linux-gnuabi64)
		ARCH := mips64el
	else ifeq ($(TOOLCHAIN),powerpc-linux-gnu)
		ARCH := powerpc32
	else ifeq ($(TOOLCHAIN),powerpc64-linux-gnu)
		ARCH := powerpc64
	else ifeq ($(TOOLCHAIN),riscv64-linux-gnu)
		ARCH := riscv64
	else ifeq ($(TOOLCHAIN),s390x-linux-gnu)
		ARCH := s390x
	else ifeq ($(TOOLCHAIN),sparc64-linux-gnu)
		ARCH := sparc64
	else ifeq ($(TOOLCHAIN),x86_64-linux-gnu)
		ARCH := x86_64
	else
		ARCH := unknown
	endif
else
	CROSS_COMPILE :=
	SYSROOT :=
	# Detect architecture based on OS (only if ARCH not already set)
	ifndef ARCH
		UNAME_S := $(shell uname -s)
		ifeq ($(UNAME_S),Darwin)
			# On macOS, detect actual architecture
			UNAME_M := $(shell uname -m)
			ifeq ($(UNAME_M),arm64)
				ARCH := arm64
			else ifeq ($(UNAME_M),x86_64)
				ARCH := x86_64
			else ifeq ($(UNAME_M),i386)
				ARCH := x86_32
			else ifeq ($(UNAME_M),i686)
				ARCH := x86_32
			else
				ARCH := $(UNAME_M)
			endif
		else
			# For Linux and other systems, default to x86_64
			ARCH := x86_64
		endif
	endif
endif
# -----------------------------------------------------------------------------
# Target type
# -----------------------------------------------------------------------------
ifndef TARGET
	TARGET := debug
endif
# -----------------------------------------------------------------------------
# Bundle runtime libraries for portable deployment
# Set BUNDLE=true for portable deployment with bundled libraries
# -----------------------------------------------------------------------------
ifndef BUNDLE
	BUNDLE := false
endif
# -----------------------------------------------------------------------------
# OS info
# -----------------------------------------------------------------------------
ifeq ($(OS),Windows_NT)
	SHELL := C:\Program Files\Git\usr\bin\sh.exe
    OS_NAME := windows
	EXE_EXT := .exe
# -----------------------------------------------------------------------------
# VS environment detection (Windows only)
# If cl.exe is not in PATH and VS has not been bootstrapped yet, set
# NEED_VS_BOOTSTRAP so the ifdef block near the build targets can intercept.
# -----------------------------------------------------------------------------
ifeq ($(RENWEB_VS_BOOTSTRAPPED),)
CL_IN_PATH := $(shell which cl 2>/dev/null)
ifeq ($(CL_IN_PATH),)
NEED_VS_BOOTSTRAP := 1
endif
endif
	OBJ_EXT := .obj
	CXX := cl
	CXXFLAGS := /std:c++20 /utf-8 /bigobj /DBOOST_ALL_NO_LIB /experimental:external /external:W0
ifeq ($(TARGET),debug)
	CXXFLAGS += /MTd /EHsc /Zi /Od /W3 /FS
	LDFLAGS += /DEBUG
else
	CXXFLAGS += /MT /EHsc /O2 /Ox /Oi /Ot /GL /GS- /Gy /W3 /FS
	LDFLAGS += /LTCG /OPT:REF /OPT:ICF
endif
	
	# Add architecture-specific flags
	ifeq ($(ARCH), x86_32)
		LDFLAGS += /MACHINE:X86
	else ifeq ($(ARCH), x86_64)
		LDFLAGS += /MACHINE:X64
	else ifeq ($(ARCH), arm64)
		LDFLAGS += /MACHINE:ARM64
	else ifeq ($(ARCH), arm32)
		LDFLAGS += /MACHINE:ARM
	endif
	
	# Detect architecture from cl.exe environment
	# Use VSCMD_ARG_TGT_ARCH if set, otherwise check PROCESSOR_ARCHITEW6432 (for 32-bit make on 64-bit system) or PROCESSOR_ARCHITECTURE
	ifdef VSCMD_ARG_TGT_ARCH
		ifeq ($(VSCMD_ARG_TGT_ARCH),x86)
			ARCH := x86_32
		else ifeq ($(VSCMD_ARG_TGT_ARCH),x64)
			ARCH := x86_64
		else ifeq ($(VSCMD_ARG_TGT_ARCH),arm)
			ARCH := arm32
		else ifeq ($(VSCMD_ARG_TGT_ARCH),arm64)
			ARCH := arm64
		endif
	else ifdef PROCESSOR_ARCHITEW6432
		# This is set when running 32-bit processes on 64-bit Windows (like 32-bit make)
		ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
			ARCH := x86_64
		else ifeq ($(PROCESSOR_ARCHITEW6432),ARM64)
			ARCH := arm64
		endif
	else ifdef PROCESSOR_ARCHITECTURE
		ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
			ARCH := x86_64
		else ifeq ($(PROCESSOR_ARCHITECTURE),x86)
			ARCH := x86_32
		else ifeq ($(PROCESSOR_ARCHITECTURE),ARM64)
			ARCH := arm64
		endif
	else
		# Default to x86_64 if no architecture can be detected
		ARCH := x86_64
	endif
else
	SHELL := /bin/sh
    UNAME_S := $(shell uname -s)
	EXE_EXT :=
	OBJ_EXT := .o
    ifeq ($(UNAME_S),Linux)
        OS_NAME := linux
		CXX := $(CROSS_COMPILE)g++
		CXXFLAGS := -MMD -MP -D_GNU_SOURCE
		ifeq ($(TARGET), debug)
			CXXFLAGS += $(SYSROOT) -g -O0 -Wall -Wextra -Wno-missing-braces -Wcast-qual -Wpointer-arith -Wunused 
		else
			CXXFLAGS += $(SYSROOT) -O3 -flto -s
		endif
		# For cross-compilation, add Boost 1.90 include path
		ifdef TOOLCHAIN
			CXXFLAGS += -isystem /usr/$(TOOLCHAIN)/usr/local/include
		endif
		# For x86_32 builds on Linux, use -m32 flag if TOOLCHAIN not set
		ifeq ($(ARCH),x86_32)
			ifndef TOOLCHAIN
				CXXFLAGS += -m32
			endif
		endif
    else ifeq ($(UNAME_S),Darwin)
        OS_NAME := macos
		CXX := clang++
		CXXFLAGS := -std=c++17 -MMD -MP -mmacosx-version-min=10.15
		LDFLAGS += -mmacosx-version-min=10.15
		ifeq ($(TARGET), debug)
			CXXFLAGS += -g -O0 -Wall -Wextra -Wno-missing-braces -Wcast-qual -Wpointer-arith -Wunused 
		else
			CXXFLAGS += -O3 -flto
		endif
		# Support for architecture-specific flags (for cross-compilation)
		ifdef ARCH_FLAGS
			CXXFLAGS += $(ARCH_FLAGS)
			LDFLAGS += $(ARCH_FLAGS)
		endif
		# For x86_32 builds on macOS, use -m32 flag
		ifeq ($(ARCH),x86_32)
			CXXFLAGS += -m32
		endif
    else
        $(error Unknown operating system detected. Don't know how to proceed :/)
    endif
endif
LINKTYPE := static
# -----------------------------------------------------------------------------
# Utility stuff for the makefile
# -----------------------------------------------------------------------------
RESET   := \033[0m
RED     := \033[31m
GREEN   := \033[32m
YELLOW  := \033[33m
BLUE    := \033[34m
MAGENTA := \033[35m
CYAN    := \033[36m
BOLD    := \033[1m
define describe
	@printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET) $(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "$(1)" "$(2)" "$(3)" "$(4)"
endef
define warn
	@printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET) $(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "$(1)" "$(2)" "$(3)" "$(4)"
endef
define step
	@printf "$(CYAN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET) $(CYAN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "$(1)" "$(2)" "$(3)" "$(4)"
endef
# -----------------------------------------------------------------------------
# Paths 
# -----------------------------------------------------------------------------
BUILD_PATH :=  ./build
COPY_PATH :=   ./build
LIC_PATH :=    ./licenses
INFO_PATH :=   ./info.json
CONFIG_PATH := ./config.json
ASSETS_PATH := ./web/example/assets
SRC_PATH :=    ./src
OBJ_PATH :=    $(SRC_PATH)/.build
INC_PATH :=    ./include
PATCH_PATH :=  ./patches
EXE_NAME := $(shell sed -n 's/.*"title"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' ./info.json | tr '[:upper:]' '[:lower:]' | sed 's/[[:space:]_]/-/g' | xargs)
EXE_VERSION := $(shell sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' ./info.json | xargs)
EXE := $(EXE_NAME)-$(EXE_VERSION)-$(OS_NAME)-$(ARCH)$(EXE_EXT)
ifeq ($(OS_NAME), windows)
	# Boost paths - prefer C:/local, fallback to external/boost
	BOOST_LOCAL := $(wildcard C:/local/boost_*)
	ifneq ($(BOOST_LOCAL),)
		BOOST_ROOT := $(firstword $(BOOST_LOCAL))
		BOOST_INCLUDE := /external:I$(BOOST_ROOT)
	else
		BOOST_ROOT := external/boost
		BOOST_INCLUDE := /external:I$(BOOST_ROOT)
	endif
	
EXTERN_INC_PATHS := \
	$(BOOST_INCLUDE) \
	$(addprefix /I, $(wildcard external/cpp-httplib/)) \
	$(addprefix /I, $(wildcard external/spdlog/)) \
	$(addprefix /I, $(wildcard external/spdlog/include)) \
	$(addprefix /I, $(wildcard external/webview/)) \
	$(addprefix /I, $(wildcard external/webview2_sdk/)) \
	/Iexternal/webview2_sdk/build/native/include \
	/Iexternal/webview2_sdk/build/native/include/webview2 \
	$(addprefix /I, external/webview/core/include) 
else 
EXTERN_INC_PATHS := \
	$(addprefix -I, $(wildcard external/*/)) \
	$(addprefix -I, $(wildcard external/*/include)) \
	$(addprefix -I, $(wildcard external/boost/libs/*/include)) \
	$(addprefix -I, $(wildcard external/boost/libs/*/*/include)) \
	$(addprefix -I, $(wildcard external/boost/libs/*/*/*/include)) \
	$(addprefix -I, external/webview/core/include) 
endif
# -----------------------------------------------------------------------------
# Static Linked Libraries
# -----------------------------------------------------------------------------
ifeq ($(OS_NAME), windows)
	# Architecture-specific Boost library paths - prefer C:/local, fallback to external/boost
	BOOST_LOCAL := $(wildcard C:/local/boost_*)
	ifneq ($(BOOST_LOCAL),)
		BOOST_ROOT := $(firstword $(BOOST_LOCAL))
		# Extract version from directory name (e.g., boost_1_82_0 -> 1_82)
		BOOST_VERSION := $(shell echo $(notdir $(BOOST_ROOT)) | sed 's/boost_\([0-9]*_[0-9]*\).*/\1/')
		ifeq ($(ARCH), x86_64)
			BOOST_LIB_PATH := $(BOOST_ROOT)/lib64-msvc-14.3-static
			BOOST_LIB_SUFFIX := -vc143-mt-x64-$(BOOST_VERSION).lib
			BOOST_SYSTEM_LIB :=
		else ifeq ($(ARCH), x86_32)
			BOOST_LIB_PATH := $(BOOST_ROOT)/lib32-msvc-14.3-static
			BOOST_LIB_SUFFIX := -vc143-mt-x32-$(BOOST_VERSION).lib
			BOOST_SYSTEM_LIB :=
		else ifeq ($(ARCH), arm64)
			BOOST_LIB_PATH := $(BOOST_ROOT)/lib64-arm-msvc-14.3-static
			BOOST_LIB_SUFFIX := -vc143-mt-a64-$(BOOST_VERSION).lib
			BOOST_SYSTEM_LIB :=
		else
			$(error Unsupported architecture: $(ARCH))
		endif
	else
		BOOST_ROOT := external/boost
		# Check if standard stage/lib exists first (plain Boost build without arch subdir)
		ifneq ($(wildcard $(BOOST_ROOT)/stage/lib/*.lib),)
			BOOST_LIB_PATH := $(BOOST_ROOT)/stage/lib
			BOOST_LIB_SUFFIX := .lib
			BOOST_SYSTEM_LIB :=
		else
			# Arch-specific layout built by build_all_archs.sh
			# Dirs: x64/x86/arm64   File tags: x64/x32/a64
			ifeq ($(ARCH), x86_64)
				BOOST_LIB_PATH := $(BOOST_ROOT)/stage/x64/lib
				BOOST_LIB_ARCH_TAG := x64
			else ifeq ($(ARCH), x86_32)
				BOOST_LIB_PATH := $(BOOST_ROOT)/stage/x86/lib
				BOOST_LIB_ARCH_TAG := x32
			else ifeq ($(ARCH), arm64)
				BOOST_LIB_PATH := $(BOOST_ROOT)/stage/arm64/lib
				BOOST_LIB_ARCH_TAG := a64
			else
				$(error Unsupported architecture: $(ARCH))
			endif
			ifeq ($(TARGET),debug)
				BOOST_LIB_SUFFIX := -mt-sgd-$(BOOST_LIB_ARCH_TAG).lib
			else
				BOOST_LIB_SUFFIX := -mt-s-$(BOOST_LIB_ARCH_TAG).lib
			endif
			BOOST_SYSTEM_LIB :=
		endif
	endif
	
	# Determine library prefix and link flags based on source (C:/local vs external/boost)
	ifneq ($(BOOST_LOCAL),)
		# C:/local uses "boost_" prefix (no "lib")
		BOOST_LIB_PREFIX := boost_
	else
		# external/boost built libs use "libboost_" prefix
		BOOST_LIB_PREFIX := libboost_
	endif
	
	LIBS := \
		comdlg32.lib \
		$(BOOST_LIB_PATH)/$(BOOST_LIB_PREFIX)program_options$(BOOST_LIB_SUFFIX) \
		$(BOOST_LIB_PATH)/$(BOOST_LIB_PREFIX)json$(BOOST_LIB_SUFFIX) \
		$(BOOST_LIB_PATH)/$(BOOST_LIB_PREFIX)filesystem$(BOOST_LIB_SUFFIX) \
		$(BOOST_SYSTEM_LIB)
endif
ifeq ($(OS_NAME), macos)
	LIBS := -L./external/boost/stage/lib -lboost_program_options -lboost_json -framework Cocoa -framework WebKit -ldl 
endif
ifeq ($(OS_NAME), linux)
	ifdef TOOLCHAIN
		# For all cross-compilation targets, use explicit sysroot path and link boost statically
		LIBS := -L/usr/$(TOOLCHAIN)/usr/local/lib -Wl,-Bstatic -lboost_program_options -lboost_json -lboost_container -Wl,-Bdynamic -lpthread -ldl -latomic
		LDFLAGS := --sysroot=/usr/$(TOOLCHAIN) -L/lib -L/lib64 -L/usr/lib -L/usr/lib64
	else
		BOOST_STAGE_PATH := external/boost/stage/lib
		LIBS := $(BOOST_STAGE_PATH)/libboost_program_options.a $(BOOST_STAGE_PATH)/libboost_json.a $(BOOST_STAGE_PATH)/libboost_container.a -ldl
		LDFLAGS :=
	endif
endif
# -----------------------------------------------------------------------------
# Dynamic Linked Libraries
# -----------------------------------------------------------------------------
ifeq ($(OS_NAME),linux)
    ifdef TOOLCHAIN
        PKG_CONFIG := pkg-config
        PKG_CONFIG_PATH := /usr/$(TOOLCHAIN)/usr/local/lib/pkgconfig:/usr/$(TOOLCHAIN)/usr/lib/pkgconfig:/usr/$(TOOLCHAIN)/usr/lib/i386-linux-gnu/pkgconfig:/usr/$(TOOLCHAIN)/usr/share/pkgconfig:/usr/$(TOOLCHAIN)/lib/pkgconfig
        PKG_CONFIG_LIBDIR := /usr/$(TOOLCHAIN)/usr/local/lib/pkgconfig
        PKG_CONFIG_SYSROOT_DIR := /usr/$(TOOLCHAIN)
        PKG_CFLAGS := $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) PKG_CONFIG_SYSROOT_DIR=$(PKG_CONFIG_SYSROOT_DIR) $(PKG_CONFIG) --cflags gtk+-3.0 webkit2gtk-4.1)
        PKG_LIBS   := $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) PKG_CONFIG_SYSROOT_DIR=$(PKG_CONFIG_SYSROOT_DIR) $(PKG_CONFIG) --libs gtk+-3.0 webkit2gtk-4.1)
    else
        PKG_CONFIG := pkg-config
        # Prefer /usr/local so the DEVELOPER_MODE-enabled WebKit (installed by
        # rebuild-webkit-devmode.sh) takes precedence over the apt system webkit.
        PKG_CFLAGS := $(shell PKG_CONFIG_PATH=/usr/local/lib/pkgconfig $(PKG_CONFIG) --cflags gtk+-3.0 webkit2gtk-4.1)
        PKG_LIBS   := $(shell PKG_CONFIG_PATH=/usr/local/lib/pkgconfig $(PKG_CONFIG) --libs gtk+-3.0 webkit2gtk-4.1)
    endif
endif
# -----------------------------------------------------------------------------
# Source and Object files
# -----------------------------------------------------------------------------
SRCS := $(wildcard $(SRC_PATH)/*.cpp) $(wildcard $(SRC_PATH)/managers/*.cpp)
OBJS := $(patsubst $(SRC_PATH)/%.cpp, $(OBJ_PATH)/%$(OBJ_EXT), $(SRCS))

ifeq ($(OS_NAME), windows)
	RC := rc.exe
	RES_FILE := $(OBJ_PATH)/app.res
	OBJS += $(RES_FILE)
endif

# -----------------------------------------------------------------------------
# VS auto-bootstrap (active only when cl.exe is absent from PATH)
# Writes a temp .bat that sources vcvarsall, adds Git Bash's usr/bin to PATH
# so make.exe stays reachable from cmd, then re-execs make with the original
# goals and variable overrides.  RENWEB_VS_BOOTSTRAPPED=1 prevents re-entry.
#
# The ifdef/else below is CRITICAL: real build targets and bootstrap targets
# are defined exclusively — whichever branch is taken is the only one Make
# sees, so there is no duplicate-recipe override problem.
# -----------------------------------------------------------------------------
ifdef NEED_VS_BOOTSTRAP
VCVARS_BAT    := vcvars64.bat
ifeq ($(ARCH),x86_32)
VCVARS_BAT    := vcvars32.bat
else ifeq ($(ARCH),arm64)
VCVARS_BAT    := vcvarsamd64_arm64.bat
endif
_VS_GOALS := $(if $(MAKECMDGOALS),$(MAKECMDGOALS),all)
_VS_VARS  := $(strip $(foreach v,TARGET BUNDLE ARCH LINKTYPE,\
               $(if $(filter-out undefined default,$(origin $v)),$v=$($v))))
_vs_bootstrap:
	@VSWHERE="C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"; \
	if [ ! -f "$$VSWHERE" ]; then \
		printf "\033[31;1mError\033[0m cl.exe not in PATH and vswhere.exe not found.\nInstall Visual Studio with the 'Desktop development with C++' workload.\n"; \
		exit 1; \
	fi; \
	TMP_VS="/tmp/_rw_vs.txt"; \
	printf "\033[36;1mBootstrapping\033[0m Locating Visual Studio toolchain...\n"; \
	"$$VSWHERE" -latest -products '*' \
		-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
		-find "VC/Auxiliary/Build/$(VCVARS_BAT)" \
		> "$$TMP_VS" 2>/dev/null; \
	if [ ! -s "$$TMP_VS" ]; then \
		printf "\033[31;1mError\033[0m No VS C++ build tools found.\nInstall 'Desktop development with C++' in the Visual Studio Installer.\n"; \
		exit 1; \
	fi; \
	VCBAT=$$(tr -d '\r' < "$$TMP_VS" | head -1); \
	rm -f "$$TMP_VS"; \
	printf "\033[36;1mBootstrapping\033[0m Capturing VS environment from: %s\n" "$$VCBAT"; \
	_esc=$$(printf '%s' "$$VCBAT" | sed 's/[^0-9A-Za-z]/^&/g'); \
	ENV_OUT=$$(MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' \
		cmd.exe /s /c " ; $$_esc && set" </dev/null 2>/dev/null | tr -d '\r'); \
	if [ -z "$$ENV_OUT" ]; then \
		printf "\033[31;1mError\033[0m cmd.exe returned empty output — vcvarsall.bat may have failed.\nCheck that the 'Desktop development with C++' workload is installed.\n"; \
		exit 1; \
	fi; \
	_vs_include=$$(printf '%s\n' "$$ENV_OUT" | grep -i '^INCLUDE=' | head -1 | cut -d= -f2-); \
	if [ -z "$$_vs_include" ]; then \
		printf "\033[31;1mError\033[0m VS environment not initialized (INCLUDE not set).\nCheck that the 'Desktop development with C++' workload is installed.\n"; \
		exit 1; \
	fi; \
	_vs_path=$$(printf '%s\n' "$$ENV_OUT" | grep -i '^Path=' | head -1 | cut -d= -f2-); \
	_vs_lib=$$(printf '%s\n' "$$ENV_OUT" | grep -i '^LIB=' | head -1 | cut -d= -f2-); \
	_vs_libpath=$$(printf '%s\n' "$$ENV_OUT" | grep -i '^LIBPATH=' | head -1 | cut -d= -f2-); \
	if [ -n "$$_vs_path" ]; then \
		_posix_path=$$(cygpath --path --unix "$$_vs_path" 2>/dev/null); \
		[ -n "$$_posix_path" ] && export PATH="$$_posix_path:$$PATH"; \
	fi; \
	[ -n "$$_vs_include" ] && export INCLUDE="$$_vs_include"; \
	[ -n "$$_vs_lib" ]     && export LIB="$$_vs_lib"; \
	[ -n "$$_vs_libpath" ] && export LIBPATH="$$_vs_libpath"; \
	printf "\033[36;1mBootstrapping\033[0m VS environment ready. Starting build...\n"; \
	export RENWEB_VS_BOOTSTRAPPED=1; \
	$(MAKE) -f makefile $(_VS_GOALS) $(_VS_VARS)
$(_VS_GOALS): _vs_bootstrap
.PHONY: _vs_bootstrap $(_VS_GOALS)
else
# -----------------------------------------------------------------------------
# Build target
# -----------------------------------------------------------------------------
all: $(BUILD_PATH)/$(EXE) copy-files
# -----------------------------------------------------------------------------
# RULE: Link all object files into executable
# -----------------------------------------------------------------------------
$(BUILD_PATH)/$(EXE): $(OBJS) | $(BUILD_PATH)
	$(call step,Linking Executable,$@,of link type,$(LINKTYPE))
ifeq ($(LINKTYPE),shared)
	$(call warn,Shared for unix isn't implemented yet! Using static)
ifeq ($(OS_NAME),windows)
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) $^ $(LIBS) $(PKG_LIBS) /link $(LDFLAGS) /out:$@
else
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) $^ $(LDFLAGS) $(LIBS) $(PKG_LIBS) -o $@
endif
else
ifeq ($(OS_NAME),windows)
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) $^ $(LIBS) $(PKG_LIBS) /link $(LDFLAGS) /out:$@
else
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) $^ $(LDFLAGS) $(LIBS) $(PKG_LIBS) -o $@
endif
endif
	$(call step,Linking Executable [DONE],$@)

# -----------------------------------------------------------------------------
# RULE: Compile Windows resource file
# Template tokens (@RC_*@) are filled from info.json before rc.exe is invoked.
# -----------------------------------------------------------------------------
ifeq ($(OS_NAME), windows)
$(RES_FILE): resource/app.rc resource/app.ico resource/app.manifest info.json | $(OBJ_PATH)
	$(call step,Compiling Resource File,$@)
	@INFO=./info.json; \
	 RC_TITLE=$$(sed -n 's/.*"title"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$$INFO" 2>/dev/null | xargs 2>/dev/null); \
	 RC_TITLE=$${RC_TITLE:-}; \
	 RC_AUTHOR=$$(sed -n 's/.*"author"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$$INFO" 2>/dev/null | xargs 2>/dev/null); \
	 RC_AUTHOR=$${RC_AUTHOR:-}; \
	 RC_DESCRIPTION=$$(sed -n 's/.*"description"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$$INFO" 2>/dev/null | xargs 2>/dev/null); \
	 RC_DESCRIPTION=$${RC_DESCRIPTION:-}; \
	 RC_COPYRIGHT=$$(sed -n 's/.*"copyright"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$$INFO" 2>/dev/null | xargs 2>/dev/null); \
	 RC_COPYRIGHT=$${RC_COPYRIGHT:-}; \
	 RC_VERSION_CSV=$$(echo "$(EXE_VERSION)" | awk -F. 'NF>=3{printf "%s,%s,%s,0",$$1,$$2,$$3} NF<3{print "0,0,0,0"}' 2>/dev/null); \
	 RC_VERSION_CSV=$${RC_VERSION_CSV:-0,0,0,0}; \
	 RC_VERSION_STR=$$([ -n "$(EXE_VERSION)" ] && echo "$(EXE_VERSION).0" || echo "0.0.0.0"); \
	 RC_EXE_FILENAME=$${EXE:-$(EXE)}; \
	 RC_EXE_FILENAME=$${RC_EXE_FILENAME:-unknown.exe}; \
	 { printf '\xEF\xBB\xBF'; sed \
	     -e "s|@RC_TITLE@|$$RC_TITLE|g" \
	     -e "s|@RC_AUTHOR@|$$RC_AUTHOR|g" \
	     -e "s|@RC_DESCRIPTION@|$$RC_DESCRIPTION|g" \
	     -e "s|@RC_COPYRIGHT@|$$RC_COPYRIGHT|g" \
	     -e "s|@RC_VERSION_CSV@|$$RC_VERSION_CSV|g" \
	     -e "s|@RC_VERSION_STR@|$$RC_VERSION_STR|g" \
	     -e "s|@RC_EXE_FILENAME@|$$RC_EXE_FILENAME|g" \
	     resource/app.rc; } > $(OBJ_PATH)/app_filled.rc
	$(RC) /fo $@ /I resource $(OBJ_PATH)/app_filled.rc
	$(call step,Compiling Resource File [DONE],$@)
endif
# -----------------------------------------------------------------------------
# RULE: Special compilation for window_functions.cpp and app.cpp on macOS (Objective-C++)
# -----------------------------------------------------------------------------
ifeq ($(OS_NAME), macos)
$(OBJ_PATH)/window_functions$(OBJ_EXT): $(SRC_PATH)/window_functions.cpp | $(OBJ_PATH)
	$(call step,Compiling (Objective-C++),$<)
	$(CXX) $(CXXFLAGS) -x objective-c++ -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) -c $< -o $@
	$(call step,Compiling [DONE],$<)

$(OBJ_PATH)/app$(OBJ_EXT): $(SRC_PATH)/app.cpp | $(OBJ_PATH)
	$(call step,Compiling (Objective-C++),$<)
	$(CXX) $(CXXFLAGS) -x objective-c++ -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) -c $< -o $@
	$(call step,Compiling [DONE],$<)
endif
# -----------------------------------------------------------------------------
# RULE: Compile source files to object files
# -----------------------------------------------------------------------------
$(OBJ_PATH)/%$(OBJ_EXT): $(SRC_PATH)/%.cpp | $(OBJ_PATH)
	@mkdir -p $(dir $@)
	$(call step,Compiling,$<)
ifeq ($(OS_NAME),windows)
ifeq ($(LINKTYPE),shared)
	$(CXX) $(CXXFLAGS) /I$(PATCH_PATH) /I$(INC_PATH) /MD /DBOOST_ALL_DYN_LINK $(EXTERN_INC_PATHS) /c $< /Fo$@
else
	$(CXX) $(CXXFLAGS) /I$(PATCH_PATH) /I$(INC_PATH) $(EXTERN_INC_PATHS) /c $< /Fo$@
endif
else 
ifeq ($(LINKTYPE),shared)
	$(call warn,Shared for unix isn't implemented yet! Using static)
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) -c $< -o $@
else
	$(CXX) $(CXXFLAGS) $(PKG_CFLAGS) -I$(PATCH_PATH) -I$(INC_PATH) $(EXTERN_INC_PATHS) -c $< -o $@
endif
endif
	$(call step,Compiling [DONE],$<)
# -----------------------------------------------------------------------------
# RULE: Make sure build directory exists
# -----------------------------------------------------------------------------
$(BUILD_PATH):
	$(call step,Build Path,Making path at $@)
	mkdir -p $@
	$(call step,Build Path [DONE],Making path at $@)
# -----------------------------------------------------------------------------
# RULE: Make sure object directory exists
# -----------------------------------------------------------------------------
$(OBJ_PATH):
	$(call step,Object Path,Making path at $@)
	mkdir -p $@
	$(call step,Object Path [DONE],Making path at $@)

# -----------------------------------------------------------------------------
# COMMAND: Remove build files
# -----------------------------------------------------------------------------
clean:
	$(call step,Cleaning)
	rm -rf $(wildcard $(BUILD_PATH)/$(EXE_NAME)-*)
	rm -rf $(OBJ_PATH)/*
	$(call step,Cleaning [DONE])
# -----------------------------------------------------------------------------
# COMMAND: Remove build files and exe
# -----------------------------------------------------------------------------
clear:
	$(call step,Clearing)
	rm -rf $(OBJ_PATH)/*
	$(call step,Clearing [DONE])
# -----------------------------------------------------------------------------
# COMMAND: Run the program
# -----------------------------------------------------------------------------
run: $(BUILD_PATH)/$(EXE)
	$(call step,Running)
	./$(BUILD_PATH)/$(EXE) $(ARGS)
	$(call step,Running [DONE])
# -----------------------------------------------------------------------------
# COMMAND: Test the program with memory analysis tools
# Linux (valgrind):   --leak-check=full --show-leak-kinds=all
# macOS (leaks):      MallocStackLogging=1 for detailed stack traces
# Windows (drmemory): -light for faster analysis
# -----------------------------------------------------------------------------
test: $(BUILD_PATH)/$(EXE)
	$(call step,Testing)
ifeq ($(OS_NAME),linux)
	ulimit -n 20000 && valgrind --leak-check=full --show-leak-kinds=all ./$(BUILD_PATH)/$(EXE) -l0
else ifeq ($(OS_NAME),macos)
	MallocStackLogging=1 leaks --atExit -- ./$(BUILD_PATH)/$(EXE) -l0
else ifeq ($(OS_NAME),windows)
	./$(BUILD_PATH)/$(EXE) -l1
endif
	$(call step,Testing [DONE])
# -----------------------------------------------------------------------------
# COMMAND: Info about the makefile
# -----------------------------------------------------------------------------
info:
	$(call step,Displaying info)
	$(call describe,OS,$(OS_NAME))
	$(call describe,App Name,$(EXE))
	$(call describe,Compiler,$(CXX))
	$(call describe,Target,$(TARGET))
	$(call describe,Build Path,$(BUILD_PATH))
	$(call describe,Source Path,$(SRC_PATH))
	$(call describe,Object Path,$(OBJ_PATH))
	$(call describe,Include Path,$(INC_PATH))
	$(call step,Displaying info [DONE])

# -----------------------------------------------------------------------------
# COMMAND: Display help info
# -----------------------------------------------------------------------------
help:
	@echo "Usage:"
	@echo "  make TARGET=debug      Build the application in debug mode"
	@echo "  make TARGET=release    Build the application in release mode"
	@echo "  make BUNDLE=true       Bundle runtime libraries for portable deployment (Linux/macOS)"
	@echo "  make verify-bundle     Verify bundled libraries are complete (run after BUNDLE=true)"
	@echo "  make sub_modules       Builds the submodules"
	@echo "  make clean             Clean up the build directory"
	@echo "  make run               Build and run the application"
	@echo "  make test              Build and test the application"
	@echo "  make info              Displays info set in the makefile"
	@echo "  make help              Display this help message"
# -----------------------------------------------------------------------------
# Phony targets
# -----------------------------------------------------------------------------
.PHONY: all clean run help copy-files bundle-libs verify-bundle
# -----------------------------------------------------------------------------
# PHONY TARGET: Copy files
# -----------------------------------------------------------------------------
copy-files: $(BUILD_PATH)/$(EXE) bundle-libs
	$(call step,Copy Files, Copying Files at $@)
	mkdir -p $(COPY_PATH)
	cp -R $(LIC_PATH) $(COPY_PATH)
	cp $(INFO_PATH) $(COPY_PATH)/info.json
	cp $(CONFIG_PATH) $(COPY_PATH)/config.json
	rm -rf $(COPY_PATH)/assets
	cp -r $(ASSETS_PATH) $(COPY_PATH)/assets
	$(call step,Copy Files, Copying example pages)
	rm -rf $(COPY_PATH)/content
	@mkdir -p $(COPY_PATH)/content
	@if [ -d "./web/example/pages" ]; then \
		for page_dir in ./web/example/pages/*; do \
			if [ -d "$$page_dir" ]; then \
				page_name=$$(basename "$$page_dir"); \
				cp -r "$$page_dir" "$(COPY_PATH)/content/$$page_name"; \
			fi; \
		done; \
	fi
	$(call step,Copy Files, Copying API files to pages)
	@if [ -d "./web/api" ]; then \
		for page_dir in $(COPY_PATH)/content/*; do \
			if [ -d "$$page_dir" ]; then \
				for file in index.js index.js.map index.d.ts; do \
					if [ -f "./web/api/$$file" ]; then \
						cp "./web/api/$$file" "$$page_dir/"; \
					fi; \
				done; \
			fi; \
		done; \
	fi
	$(call step,Copy Files [DONE] Copying Files at $@)
# -----------------------------------------------------------------------------
# PHONY TARGET: Bundle runtime libraries for portable deployment
# -----------------------------------------------------------------------------
bundle-libs: $(BUILD_PATH)/$(EXE)
ifeq ($(BUNDLE),true)
ifeq ($(OS_NAME),linux)
	$(call step,Bundling Libraries,Copying runtime dependencies for portable deployment)
	@# Bundle layout: all .so files land in lib-ARCH/.  A webkit2gtk-4.1/
	@# subdirectory holds the WebKit subprocess helpers.  bundle_exec.sh
	@# invokes the bundled ld-linux linker with --library-path lib-ARCH/
	@# so the glibc-linked binary runs correctly on musl hosts (Alpine)
	@# without touching any host-installed shared libraries.
	@rm -rf $(BUILD_PATH)/lib-$(ARCH)
	@mkdir -p $(BUILD_PATH)/lib-$(ARCH)
	@mkdir -p $(BUILD_PATH)/lib-$(ARCH)/glvnd/egl_vendor.d
	$(call step,Collecting Dependencies,Gathering shared libraries for $(ARCH))
ifdef TOOLCHAIN
	@# ── Phase 1 (cross): BFS walk over ELF NEEDED dependencies ──────────────
	@# Starting from the main executable, recursively collect every shared
	@# library listed in DT_NEEDED sections.  Uses the cross-compiler readelf
	@# to read foreign ELF headers.  ld-linux* and linux-vdso* are excluded
	@# here — the dynamic linker (PT_INTERP) is extracted and copied below.
	@SYSROOT_PATH=/usr/$(TOOLCHAIN); \
	if [ -d "$$SYSROOT_PATH/lib" ]; then \
		SEARCH_DIRS="$$SYSROOT_PATH/lib $$SYSROOT_PATH/lib64 $$SYSROOT_PATH/usr/lib $$SYSROOT_PATH/usr/lib64 $$SYSROOT_PATH/usr/local/lib $$SYSROOT_PATH/usr/local/lib64 /usr/lib/$(TOOLCHAIN)"; \
		for _gd in /usr/lib/gcc-cross/$(TOOLCHAIN)/*/; do \
			[ -d "$$_gd" ] && SEARCH_DIRS="$$SEARCH_DIRS $$_gd"; \
		done; \
		TODO_LIBS="$(BUILD_PATH)/$(EXE)"; \
		QUEUED=" "; \
		while [ -n "$$TODO_LIBS" ]; do \
			CURRENT_LIB=$$(echo "$$TODO_LIBS" | head -n1); \
			TODO_LIBS=$$(echo "$$TODO_LIBS" | tail -n +2); \
			NEEDED=$$($(TOOLCHAIN)-readelf -d "$$CURRENT_LIB" 2>/dev/null | grep 'NEEDED' | awk '{print $$5}' | tr -d '[]'); \
			for lib in $$NEEDED; do \
				case " $$QUEUED " in *" $$lib "*) continue ;; esac; \
				case "$$lib" in \
						ld-linux*|linux-vdso*) continue ;; \
				esac; \
				for search_dir in $$SEARCH_DIRS; do \
					if [ -f "$$search_dir/$$lib" ]; then \
						cp -L "$$search_dir/$$lib" $(BUILD_PATH)/lib-$(ARCH)/ 2>/dev/null || true; \
						$(TOOLCHAIN)-strip --strip-unneeded $(BUILD_PATH)/lib-$(ARCH)/$$lib 2>/dev/null || true; \
						QUEUED="$$QUEUED$$lib "; \
						TODO_LIBS="$$(printf '%s\n%s' "$$TODO_LIBS" "$$search_dir/$$lib")"; \
						break; \
					fi; \
				done; \
			done; \
		done; \
		LD_INTERP=$$($(TOOLCHAIN)-readelf -l "$(BUILD_PATH)/$(EXE)" 2>/dev/null | grep 'Requesting program interpreter' | sed 's/.*interpreter: //;s/\].*//'); \
		if [ -n "$$LD_INTERP" ]; then \
			LD_NAME=$$(basename "$$LD_INTERP"); \
			for search_dir in $$SEARCH_DIRS; do \
				if [ -f "$$search_dir/$$LD_NAME" ]; then \
					cp -L "$$search_dir/$$LD_NAME" $(BUILD_PATH)/lib-$(ARCH)/ 2>/dev/null || true; \
					chmod +x $(BUILD_PATH)/lib-$(ARCH)/$$LD_NAME 2>/dev/null || true; \
					break; \
				fi; \
			done; \
		fi; \
		LIB_COUNT=$$(ls -1 $(BUILD_PATH)/lib-$(ARCH)/*.so* 2>/dev/null | wc -l); \
		if [ $$LIB_COUNT -gt 0 ]; then \
			printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Libraries Copied" "$$LIB_COUNT libraries from $(TOOLCHAIN) sysroot"; \
		else \
			printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "No libraries found for $(TOOLCHAIN)"; \
		fi; \
	else \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "Sysroot not found at $$SYSROOT_PATH"; \
	fi
else
	@# ── Phase 1 (native): collect deps via ldd ──────────────────────────────
	@# On the build host, ldd resolves the executable's runtime deps against
	@# the local dynamic linker, giving the exact set of .so paths to bundle.
	@LIBS=$$(ldd $(BUILD_PATH)/$(EXE) 2>/dev/null | grep -v 'linux-vdso\|ld-linux' | grep '=>' | awk '{print $$3}' | grep -v '^$$' | sort -u); \
	if [ -n "$$LIBS" ]; then \
		echo "$$LIBS" | xargs -I {} cp -L {} $(BUILD_PATH)/lib-$(ARCH)/ 2>/dev/null || true; \
		LIB_COUNT=$$(ls -1 $(BUILD_PATH)/lib-$(ARCH)/*.so* 2>/dev/null | wc -l); \
		printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Libraries Copied" "$$LIB_COUNT shared libraries bundled"; \
	else \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "No libraries found to bundle"; \
	fi; \
	LD_INTERP=$$(readelf -l $(BUILD_PATH)/$(EXE) 2>/dev/null | grep 'Requesting program interpreter' | sed 's/.*interpreter: //;s/\].*//'); \
	if [ -n "$$LD_INTERP" ] && [ -f "$$LD_INTERP" ]; then \
		LD_NAME=$$(basename "$$LD_INTERP"); \
		cp -L "$$LD_INTERP" $(BUILD_PATH)/lib-$(ARCH)/"$$LD_NAME" 2>/dev/null || true; \
		chmod +x $(BUILD_PATH)/lib-$(ARCH)/"$$LD_NAME" 2>/dev/null || true; \
	fi
endif
	@# ── Phase 2: (removed) ────────────────────────────────────────────────
	@# libepoxy was rebuilt with -Dglx=no -Dx11=false for all arches so it
	@# only contacts libEGL.so.1 (already in the bundle via BFS).  It no
	@# longer dlopen's libGL.so.1, libGLX.so.0, or libOpenGL.so.0, so there
	@# is nothing extra to copy here.
	$(call step,Bundling WebKit Helpers,Copying subprocess executables and injected bundle)
	@# ── Phase 3: WebKit subprocess helpers ──────────────────────────────────
	@# WebKitGTK forks separate processes for page rendering, networking, and
	@# GPU compositing.  Their path is compiled into libwebkit2gtk-4.1 as
	@# PKGLIBEXECDIR (/usr/local/libexec/webkit2gtk-4.1).  We copy the real
	@# ELF binaries into lib-ARCH/webkit2gtk-4.1/ with a .real suffix, then
	@# generate thin #!/bin/sh wrapper scripts that invoke the bundled ld-linux
	@# linker, so every subprocess executes under the bundle's own glibc.
	@if [ -n "$(TOOLCHAIN)" ]; then \
		_wk_sysroot="/usr/$(TOOLCHAIN)"; _strip="$(TOOLCHAIN)-strip"; \
	else \
		_wk_sysroot=""; _strip="strip"; \
	fi; \
	WK_SRC=""; \
	for _cand in \
		"$${_wk_sysroot}/usr/local/libexec/webkit2gtk-4.1" \
		"$${_wk_sysroot}/lib/webkit2gtk-4.1" \
		"$${_wk_sysroot}/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1" \
		"$${_wk_sysroot}/usr/lib/i386-linux-gnu/webkit2gtk-4.1" \
	; do \
		[ -f "$$_cand/WebKitWebProcess" ] && { WK_SRC="$$_cand"; break; }; \
	done; \
	[ -z "$$WK_SRC" ] && WK_SRC="$${_wk_sysroot}/usr/local/libexec/webkit2gtk-4.1"; \
	WK_INJ_SRC="$$WK_SRC/injected-bundle"; \
	if [ ! -f "$$WK_INJ_SRC/libwebkit2gtkinjectedbundle.so" ]; then \
		WK_INJ_SRC="$${_wk_sysroot}/usr/local/lib/webkit2gtk-4.1/injected-bundle"; \
	fi; \
	WK_DST="$(BUILD_PATH)/lib-$(ARCH)/webkit2gtk-4.1"; \
	mkdir -p "$$WK_DST"; \
	_wk_count=0; \
	for _helper in WebKitWebProcess WebKitNetworkProcess WebKitGPUProcess; do \
		if [ -f "$$WK_SRC/$$_helper" ]; then \
			cp -L "$$WK_SRC/$$_helper" "$$WK_DST/$$_helper.real"; \
			chmod +x "$$WK_DST/$$_helper.real"; \
			$$_strip --strip-unneeded "$$WK_DST/$$_helper.real" 2>/dev/null || true; \
			_ld_f=$$(ls "$(BUILD_PATH)/lib-$(ARCH)/"ld-*.so* 2>/dev/null | head -1); \
			if [ -n "$$_ld_f" ] && command -v patchelf >/dev/null 2>&1; then \
				_ld_hash=$$(sha256sum "$$_ld_f" 2>/dev/null | cut -c1-16); \
				if [ -n "$$_ld_hash" ]; then \
					patchelf --set-interpreter "/tmp/.renweb/.so/$${_ld_hash}.so" "$$WK_DST/$$_helper.real" 2>/dev/null || true; \
				fi; \
			fi; \
			printf '#!/bin/sh\n_D=$$(cd -P "$$(dirname "$$0")" && pwd)\nLIB_DIR="$$_D/.."\nBLD=""\nfor _l in "$$LIB_DIR"/ld-*.so*; do [ -f "$$_l" ] && [ -x "$$_l" ] && { BLD="$$_l"; break; }; done\nif [ -n "$$BLD" ]; then\n    exec "$$BLD" --library-path "$$LIB_DIR" "$$_D/%s.real" "$$@"\nelse\n    exec "$$_D/%s.real" "$$@"\nfi\n' "$$_helper" "$$_helper" > "$$WK_DST/$$_helper"; \
			chmod +x "$$WK_DST/$$_helper"; \
			_wk_count=$$((_wk_count + 1)); \
		fi; \
	done; \
	if [ -f "$$WK_INJ_SRC/libwebkit2gtkinjectedbundle.so" ]; then \
		cp -L "$$WK_INJ_SRC/libwebkit2gtkinjectedbundle.so" "$$WK_DST/"; \
		printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "WebKit Helpers" "$$_wk_count subprocess helpers + injected bundle"; \
	else \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "WebKit Helpers" "$$_wk_count subprocess helpers (injected bundle not found)"; \
	fi
	$(call step,Creating Launcher,Generating bundle_exec.sh)
	@# ── Phase 4: Launcher script ─────────────────────────────────────────────
	@# Substitute @EXE_NAME@, @EXE_VERSION@, @OS_NAME@ into the template.
	@# The generated bundle_exec.sh sets all isolation env vars (GDK_BACKEND,
	@# GST_*, GIO_*, GL_*, enchant, fontconfig, webkit) then execs the binary
	@# under the bundled ld-linux dynamic linker with --library-path lib-ARCH/.
	@sed -e 's/@EXE_NAME@/$(EXE_NAME)/g' \
	     -e 's/@EXE_VERSION@/$(EXE_VERSION)/g' \
	     -e 's/@OS_NAME@/$(OS_NAME)/g' \
	     script_templates/bundle_exec.template.sh > $(BUILD_PATH)/bundle_exec.sh
	@chmod +x $(BUILD_PATH)/bundle_exec.sh
	$(call step,Bundle Complete,Run with: ./$(BUILD_PATH)/bundle_exec.sh)
	@$(MAKE) verify-bundle --no-print-directory
else ifeq ($(OS_NAME),windows)
	$(call step,Bundling Libraries,Preparing WebView2 bootstrap bundle for Windows)
	@mkdir -p $(BUILD_PATH)/lib-$(ARCH)
	@case "$(ARCH)" in \
		x86_64) WEBVIEW2_ARCH="x64" ;; \
		x86_32) WEBVIEW2_ARCH="x86" ;; \
		arm64)  WEBVIEW2_ARCH="arm64" ;; \
		*)      WEBVIEW2_ARCH="x64" ;; \
	esac; \
	if [ -f "external/webview2_sdk/build/native/$$WEBVIEW2_ARCH/WebView2Loader.dll" ]; then \
		printf "$(CYAN)$(BOLD)%-20s$(RESET) $(MAGENTA)%s$(RESET)\n" "Copying Loader" "WebView2Loader.dll for $$WEBVIEW2_ARCH"; \
		cp "external/webview2_sdk/build/native/$$WEBVIEW2_ARCH/WebView2Loader.dll" "$(BUILD_PATH)/lib-$(ARCH)/"; \
	else \
		printf "$(YELLOW)$(BOLD)%-20s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "WebView2Loader.dll not found for $$WEBVIEW2_ARCH"; \
	fi; \
	BOOTSTRAP_SRC="external/webview2_bootstraps/MicrosoftEdgeWebview2Setup.exe"; \
	BOOTSTRAP_DST="$(BUILD_PATH)/lib-$(ARCH)/MicrosoftEdgeWebview2Setup.exe"; \
	if [ -f "$$BOOTSTRAP_SRC" ]; then \
		printf "$(CYAN)$(BOLD)%-20s$(RESET) $(MAGENTA)%s$(RESET)\n" "Copying Bootstrapper" "MicrosoftEdgeWebview2Setup.exe"; \
		cp "$$BOOTSTRAP_SRC" "$$BOOTSTRAP_DST"; \
	else \
		printf "$(YELLOW)$(BOLD)%-20s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "Bootstrap installer missing at $$BOOTSTRAP_SRC"; \
		printf "$(YELLOW)$(BOLD)%-20s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "Bundle will require preinstalled WebView2 runtime"; \
	fi
	$(call step,Creating Launcher,Generating bundle_exec.bat)
	@sed -e 's/@EXE_NAME@/$(EXE_NAME)/g' \
	     -e 's/@EXE_VERSION@/$(EXE_VERSION)/g' \
	     -e 's/@OS_NAME@/$(OS_NAME)/g' \
	     script_templates/bundle_exec.template.bat > $(BUILD_PATH)/bundle_exec.bat
	$(call step,Bundle Complete,Run with: $(BUILD_PATH)/bundle_exec.bat)
else ifeq ($(OS_NAME),macos)
	@echo "macOS does not require library bundling - WebKit is a system framework"
else
	@echo "Bundling not supported for $(OS_NAME)"
endif
endif
# -----------------------------------------------------------------------------
# PHONY TARGET: Verify bundle completeness
# -----------------------------------------------------------------------------
verify-bundle:
ifeq ($(OS_NAME),linux)
	$(call step,Verifying Bundle,Checking $(ARCH) dependencies)
	@if [ ! -d "$(BUILD_PATH)/lib-$(ARCH)" ]; then \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Error" "lib-$(ARCH) not found - run: make BUNDLE=true"; \
		exit 1; \
	fi
	@cd $(BUILD_PATH) && LD_LIBRARY_PATH=./lib-$(ARCH):$$LD_LIBRARY_PATH ldd ./$(EXE) | grep "not found" && \
		(printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Error" "Missing dependencies in executable" && exit 1) || true
	@cd $(BUILD_PATH) && failed=0; \
	for lib in lib-$(ARCH)/*.so*; do \
		missing=$$(LD_LIBRARY_PATH=./lib-$(ARCH):$$LD_LIBRARY_PATH ldd "$$lib" 2>/dev/null | grep "not found"); \
		if [ -n "$$missing" ]; then \
			echo "Missing in $$lib: $$missing"; \
			failed=1; \
		fi; \
	done; \
	if [ $$failed -eq 0 ]; then \
		printf "$(CYAN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Verification Complete" "All dependencies satisfied"; \
	else \
		exit 1; \
	fi
else ifeq ($(OS_NAME),windows)
	$(call step,Verifying Bundle,Checking $(ARCH) WebView2 components)
	@if [ ! -d "$(BUILD_PATH)/lib-$(ARCH)" ]; then \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Error" "lib-$(ARCH) not found - run: make BUNDLE=true"; \
		exit 1; \
	fi
	@if [ -f "$(BUILD_PATH)/lib-$(ARCH)/WebView2Loader.dll" ]; then \
		SIZE=$$(du -h $(BUILD_PATH)/lib-$(ARCH)/WebView2Loader.dll | cut -f1); \
		printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET) $(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Loader" "Present" "Size" "$$SIZE"; \
	else \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "WebView2Loader.dll not found"; \
	fi
	@if [ -f "$(BUILD_PATH)/lib-$(ARCH)/MicrosoftEdgeWebview2Setup.exe" ]; then \
		SIZE=$$(du -h $(BUILD_PATH)/lib-$(ARCH)/MicrosoftEdgeWebview2Setup.exe | cut -f1); \
		printf "$(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET) $(GREEN)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Bootstrapper" "Present" "Size" "$$SIZE"; \
	else \
		printf "$(YELLOW)$(BOLD)%s$(RESET) $(MAGENTA)%s$(RESET)\n" "Warning" "MicrosoftEdgeWebview2Setup.exe not found"; \
	fi
	$(call step,Verification Complete,Bundle ready for deployment)
else ifeq ($(OS_NAME),macos)
	$(call step,No Bundling Needed,macOS uses system WebKit framework)
else
	$(call warn,Not Supported,Bundle verification unavailable for $(OS_NAME))
endif
# -----------------------------------------------------------------------------
# Includes
# -----------------------------------------------------------------------------
ifeq ($(OS_NAME),windows)
-include
else
-include $(OBJS:.o=.d)
endif
endif # NEED_VS_BOOTSTRAP (closes else branch)
