// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <string>
#include <map>
#include <vector>
#include <memory>
#include <filesystem>
#include "../plugin.hpp"
#include "../locate.hpp"

#ifndef _WIN32
    #include <dlfcn.h>
#else
    #include <windows.h>
#endif

namespace RenWeb {
    // Function pointer type for plugin factory
    typedef RenWeb::Plugin* (*CreatePluginFunc)(std::shared_ptr<ILogger>);
    
    class PluginManager {
        private:
            std::shared_ptr<ILogger> logger;
            
            std::map<std::string, std::unique_ptr<Plugin>> plugins;
           
            void loadPlugin(const std::filesystem::path& path) {
                try {
                    #if defined(_WIN32)
                        HMODULE handle = LoadLibraryA(path.string().c_str());
                        if (!handle) {
                            logger->error("[plugins] Failed to load plugin: " + path.string() + " - " + std::to_string(GetLastError()));
                            return;
                        }
                        
                        SetLastError(0);
                        
                        CreatePluginFunc createFunc = (CreatePluginFunc)GetProcAddress(handle, "createPlugin");
                        if (!createFunc) {
                            logger->error("[plugins] Failed to find createPlugin in: " + path.string() + " - " + std::to_string(GetLastError()));
                            FreeLibrary(handle);
                            return;
                        }
                        
                        RenWeb::Plugin* plugin_raw = createFunc(logger);
                        if (!plugin_raw) {
                            logger->error("[plugins] createPlugin returned null for: " + path.string());
                            FreeLibrary(handle);
                            return;
                        }
                    #else
                        void* handle = dlopen(path.string().c_str(), RTLD_LAZY);
                        if (!handle) {
                            logger->error("[plugins] Failed to load plugin: " + path.string() + " - " + dlerror());
                            return;
                        }
                        
                        dlerror();
                        
                        CreatePluginFunc createFunc = (CreatePluginFunc)dlsym(handle, "createPlugin");
                        const char* dlsym_error = dlerror();
                        if (dlsym_error) {
                            logger->error("[plugins] Failed to find createPlugin in: " + path.string() + " - " + dlsym_error);
                            dlclose(handle);
                            return;
                        }
                        
                        RenWeb::Plugin* plugin_raw = createFunc(logger);
                        if (!plugin_raw) {
                            logger->error("[plugins] createPlugin returned null for: " + path.string());
                            dlclose(handle);
                            return;
                        }
                    #endif
                    
                    plugins[plugin_raw->getInternalName()] = std::unique_ptr<Plugin>(plugin_raw);
                    
                    logger->info("[plugins] Loaded plugin: " + plugin_raw->getName() + " v" + 
                                plugin_raw->getVersion() + " from " + path.string());
                    
                } catch (const std::exception& e) {
                    logger->error("[plugins] Exception loading plugin " + path.string() + ": " + e.what());
                }
            };
            bool unloadPlugin(const std::string& name) {
                auto it = plugins.find(name);
                if (it != plugins.end()) {
                    plugins.erase(it);
                    logger->info("[plugins] Unloaded plugin: " + name);
                    return true;
                }
                logger->warn("[plugins] Plugin not found for unloading: " + name);
                return false;
            };
        public:
            PluginManager(
                std::shared_ptr<ILogger> logger
            ) : logger(logger) {
                this->plugins.clear();
                const std::filesystem::path plugin_path = Locate::currentDirectory() / "plugins";
                if (!std::filesystem::exists(plugin_path)) {
                    logger->warn("[plugins] Plugin directory not found: " + plugin_path.string());
                    return;
                }
                for (const auto& entry : std::filesystem::directory_iterator(plugin_path)) {
                    if (entry.is_regular_file()) {
                        const auto& path = entry.path();
                        const auto extension = path.extension().string();
                        #ifdef _WIN32
                            if (extension == ".dll") {
                                loadPlugin(path.string());
                            }
                        #elif __APPLE__
                            if (extension == ".dylib") {
                                loadPlugin(path.string());
                            }
                        #else
                            if (extension == ".so") {
                                loadPlugin(path.string());
                            }
                        #endif
                    }
                }
            };
            ~PluginManager() = default;

            PluginManager(const PluginManager&) = delete;
            PluginManager& operator=(const PluginManager&) = delete;

            const std::map<std::string, std::unique_ptr<Plugin>>& getPlugins() const {
                return plugins;
            };
            json::array getPluginList() const {
                json::array list;
                for (const auto& [name, plugin] : plugins) {
                    list.push_back(plugin->getMetadata());
                }
                return list;
            };
    };
}