// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <string>
#include <map>
#include <vector>
#include <memory>
#include <filesystem>
#include <sstream>
#include "../plugin.hpp"
#include "../locate.hpp"

#ifndef _WIN32
    #include <dlfcn.h>
#else
    #include <windows.h>
#endif

namespace RenWeb {
    typedef RenWeb::Plugin* (*CreatePluginFunc)(std::shared_ptr<ILogger>);
    typedef void            (*DestroyPluginFunc)(RenWeb::Plugin*);

#if defined(_WIN32)
    static HMODULE safe_load_library(const char* path, DWORD* out_seh_code) noexcept {
        *out_seh_code = 0;
        __try {
            return LoadLibraryA(path);
        } __except (*out_seh_code = GetExceptionCode(), EXCEPTION_EXECUTE_HANDLER) {
            return nullptr;
        }
    }
#endif

    class PluginManager {
        private:
            std::shared_ptr<ILogger> logger;

#if defined(_WIN32)
            using LibraryHandle = HMODULE;
#else
            using LibraryHandle = void*;
#endif
            
            std::map<std::string, std::shared_ptr<Plugin>> plugins;

            LibraryHandle openLibrary(const std::filesystem::path& path) {
#if defined(_WIN32)
                DWORD seh_code = 0;
                HMODULE handle = safe_load_library(path.string().c_str(), &seh_code);
                if (!handle) {
                    if (seh_code != 0) {
                        std::stringstream ss;
                        ss << std::hex << seh_code;
                        logger->error("[plugins] Failed to load plugin (SEH exception 0x" + ss.str() + "): " + path.string() +
                            " -- likely CRT mismatch. Ensure plugin is built with the same"
                            " /MTd (debug) or /MT (release) flag as the engine.");
                    } else {
                        logger->error("[plugins] Failed to load plugin: " + path.string() + " - " + std::to_string(GetLastError()));
                    }
                    return nullptr;
                }

                return handle;
#else
                void* handle = dlopen(path.string().c_str(), RTLD_LAZY);
                if (!handle) {
                    logger->error("[plugins] Failed to load plugin: " + path.string() + " - " + dlerror());
                    return nullptr;
                }

                return handle;
#endif
            }

            void closeLibrary(LibraryHandle handle) {
#if defined(_WIN32)
                if (handle) {
                    FreeLibrary(handle);
                }
#else
                if (handle) {
                    dlclose(handle);
                }
#endif
            }

            template <typename T>
            T resolveSymbol(LibraryHandle handle, const std::filesystem::path& path, const char* symbol) {
#if defined(_WIN32)
                SetLastError(0);
                FARPROC fn = GetProcAddress(handle, symbol);
                if (!fn) {
                    logger->error("[plugins] Failed to find " + std::string(symbol) + " in: " + path.string() + " - " + std::to_string(GetLastError()));
                    return nullptr;
                }
                return reinterpret_cast<T>(fn);
#else
                dlerror();
                void* fn = dlsym(handle, symbol);
                const char* dlsym_error = dlerror();
                if (dlsym_error) {
                    logger->error("[plugins] Failed to find " + std::string(symbol) + " in: " + path.string() + " - " + dlsym_error);
                    return nullptr;
                }
                return reinterpret_cast<T>(fn);
#endif
            }
           
            void loadPlugin(const std::filesystem::path& path) {
                try {
                    const LibraryHandle handle = openLibrary(path);
                    if (!handle) {
                        return;
                    }

                    const auto createFunc = resolveSymbol<CreatePluginFunc>(handle, path, "createPlugin");
                    if (!createFunc) {
                        closeLibrary(handle);
                        return;
                    }

                    const auto destroyFunc = resolveSymbol<DestroyPluginFunc>(handle, path, "destroyPlugin");
                    if (!destroyFunc) {
                        closeLibrary(handle);
                        return;
                    }

                    RenWeb::Plugin* plugin_raw = nullptr;
                    try {
                        plugin_raw = createFunc(logger);
                    } catch (const std::exception& e) {
                        logger->error("[plugins] createPlugin threw for: " + path.string() + " - " + std::string(e.what()));
                        closeLibrary(handle);
                        return;
                    } catch (...) {
                        logger->error("[plugins] createPlugin threw a non-standard exception for: " + path.string());
                        closeLibrary(handle);
                        return;
                    }

                    if (!plugin_raw) {
                        logger->error("[plugins] createPlugin returned null for: " + path.string());
                        closeLibrary(handle);
                        return;
                    }

                    std::string internal_name;
                    std::string plugin_name;
                    std::string plugin_version;
                    try {
                        internal_name = plugin_raw->getInternalName();
                        plugin_name = plugin_raw->getName();
                        plugin_version = plugin_raw->getVersion();
                    } catch (const std::exception& e) {
                        logger->error("[plugins] Failed to read plugin metadata for: " + path.string() + " - " + std::string(e.what()));
                        try {
                            destroyFunc(plugin_raw);
                        } catch (...) {
                            logger->warn("[plugins] destroyPlugin threw while cleaning up failed plugin: " + path.string());
                        }
                        closeLibrary(handle);
                        return;
                    } catch (...) {
                        logger->error("[plugins] Failed to read plugin metadata (non-standard exception) for: " + path.string());
                        try {
                            destroyFunc(plugin_raw);
                        } catch (...) {
                            logger->warn("[plugins] destroyPlugin threw while cleaning up failed plugin: " + path.string());
                        }
                        closeLibrary(handle);
                        return;
                    }

                    plugins[internal_name] = std::shared_ptr<Plugin>(plugin_raw, [destroyFunc, handle, this](Plugin* p) {
                        try {
                            destroyFunc(p);
                        } catch (const std::exception& e) {
                            logger->error("[plugins] destroyPlugin threw: " + std::string(e.what()));
                        } catch (...) {
                            logger->error("[plugins] destroyPlugin threw a non-standard exception");
                        }
                        closeLibrary(handle);
                    });
                    
                    logger->info("[plugins] Loaded plugin: " + plugin_name + " v" +
                                plugin_version + " from " + path.string());
                    
                } catch (const std::exception& e) {
                    logger->error("[plugins] Exception loading plugin " + path.string() + ": " + e.what());
                }
            };
            bool unloadPlugin(const std::string& name) {
                auto it = plugins.find(name);
                if (it != plugins.end()) {
                    plugins.erase(it);
                    logger->info("[plugins] Unloaded plugin: " + name);
                    return true;
                }
                logger->warn("[plugins] Plugin not found for unloading: " + name);
                return false;
            };
        public:
            PluginManager(
                std::shared_ptr<ILogger> logger
            ) : logger(logger) {
                this->plugins.clear();
                const std::filesystem::path plugin_path = Locate::currentDirectory() / "plugins";
                if (!std::filesystem::exists(plugin_path)) {
                    logger->warn("[plugins] Plugin directory not found: " + plugin_path.string());
                    return;
                }
                for (const auto& entry : std::filesystem::directory_iterator(plugin_path)) {
                    if (entry.is_regular_file()) {
                        const auto& path = entry.path();
                        const auto extension = path.extension().string();
                        #ifdef _WIN32
                            if (extension == ".dll") {
                                loadPlugin(path.string());
                            }
                        #elif __APPLE__
                            if (extension == ".dylib") {
                                loadPlugin(path.string());
                            }
                        #else
                            if (extension == ".so") {
                                loadPlugin(path.string());
                            }
                        #endif
                    }
                }
            };
            ~PluginManager() = default;

            PluginManager(const PluginManager&) = delete;
            PluginManager& operator=(const PluginManager&) = delete;

            const std::map<std::string, std::shared_ptr<Plugin>>& getPlugins() const {
                return plugins;
            };
            json::array getPluginList() const {
                json::array list;
                for (const auto& [name, plugin] : plugins) {
                    list.push_back(plugin->getMetadata());
                }
                return list;
            };
    };
}