// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <boost/json.hpp>
#include <csignal>

namespace json = boost::json;

typedef int32_t Pid;

namespace RenWeb {
    class IProcessManager {
        public:
            virtual ~IProcessManager() = 0;
            virtual json::object dumpProcess(Pid pid) const = 0;
            virtual json::object dumpCurrentProcess() const = 0;
            virtual json::array dumpSystemProcesses() const = 0;
            virtual json::array dumpRenWebProcesses() const = 0;
            virtual json::array dumpChildProcesses() const = 0;
            virtual json::object createSystemProcess(
                const std::vector<std::string>& args, 
                bool is_detachable = false,
                bool share_stdio = false
            ) = 0;
            virtual json::object createRenWebProcess(
                const std::vector<std::string>& pages, 
                std::vector<std::string> args = {},
                bool is_detachable = false,
                bool include_current_args = true,
                bool share_stdio = false
            ) = 0;
            virtual Pid getPid() const = 0;
            virtual void kill(Pid pid, int32_t signal = SIGINT) = 0;
            virtual void detach(Pid pid) = 0;
            virtual void send(Pid pid, const json::value& message) = 0;
            virtual std::vector<std::string> listen(Pid pid, int64_t lines = INT64_MAX, bool tail = false) const = 0;
            virtual void wait(Pid pid) = 0;
            virtual void waitAll() = 0;
            virtual void registerProcess() const = 0;
    };    
    inline IProcessManager::~IProcessManager() = default;
}