'use strict';
// rw remove <type> [args]
//   rw remove page <name>        Move page to .rw/trash/ and clean configuration
//   rw remove plugin <name|url>  Remove cached and installed plugin binaries

const fs   = require('fs');
const path = require('path');
const {
    copyDir, saveInfo,
    parseGitHubUrl, rwPluginsDir, rwTrashDir, ensureRwGitignore,
} = require('./shared');
const { ProjectState } = require('../project/project_state');

const SHARED_EXTS = ['.so', '.dylib', '.dll'];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function requireState() {
    const state = ProjectState.detect();
    if (!state) { console.error('Not inside a RenWeb project (no info.json found)'); process.exit(1); }
    return state;
}

function saveConfig(state) {
    fs.writeFileSync(state.config_path, JSON.stringify(state.config, null, 4) + '\n', 'utf8');
}

// ─── remove page ──────────────────────────────────────────────────────────────

function removePage(name) {
    if (!name) { console.error('Usage: rw remove page <name>'); process.exit(1); }

    const pageName = name.trim().toLowerCase().replace(/[\s\-]+/g, '_');
    if (pageName === '__defaults__') {
        console.error("Cannot remove '__defaults__' \u2014 it is a reserved config key");
        process.exit(1);
    }

    const state     = requireState();
    const layout    = state.layout();
    const trashSlot = `${pageName}_${Date.now()}`;
    const trashDir  = path.join(rwTrashDir(state.root), trashSlot);
    ensureRwGitignore(state.root);

    // Move primary content to trash (never deletes).
    let moved = false;
    const srcPageDir = path.join(layout.content_root, pageName);
    if (fs.existsSync(srcPageDir)) {
        const dest = path.join(trashDir, pageName);
        fs.mkdirSync(dest, { recursive: true });
        copyDir(srcPageDir, dest);
        fs.rmSync(srcPageDir, { recursive: true, force: true });
        moved = true;
        console.log(`  \u2713 Moved ${path.relative(state.root, srcPageDir)} \u2192 .rw/trash/${trashSlot}/${pageName}/`);
    }

    // Remove build output (regenerated by rw build; not the source of truth).
    if (layout.build_content_root) {
        const buildPageDir = path.join(layout.build_content_root, pageName);
        if (fs.existsSync(buildPageDir)) {
            fs.rmSync(buildPageDir, { recursive: true, force: true });
            console.log(`  \u2713 Removed build content for '${pageName}'`);
        }
    }

    if (!moved) console.warn(`  \u26a0 No content directory found for '${pageName}'`);

    // Remove from config.json.
    if (!state.config) {
        console.warn('  \u26a0 config.json not found \u2014 remove the page entry manually');
    } else if (state.config[pageName]) {
        delete state.config[pageName];
        saveConfig(state);
        console.log(`  \u2713 Removed from config.json`);
    }

    // Remove from info.json starting_pages.
    if (state.info) {
        const sp = state.info.starting_pages || [];
        if (sp.includes(pageName)) {
            state.info.starting_pages = sp.filter(p => p !== pageName);
            saveInfo(state.root, state.info);
            console.log(`  \u2713 Removed from info.json starting_pages`);
        }
    }

    if (moved)
        console.log(`\nPage '${pageName}' moved to trash.\nTo restore: cp -r .rw/trash/${trashSlot}/${pageName}/ ${path.relative(state.root, layout.content_root)}/${pageName}/\n`);
    else
        console.log();
}

// ─── remove plugin ────────────────────────────────────────────────────────────

function removePlugin(nameOrUrl) {
    if (!nameOrUrl) { console.error('Usage: rw remove plugin <name-or-repo-url>'); process.exit(1); }

    const state   = requireState();
    const info    = state.info || {};
    const plugins = Array.isArray(info.plugins) ? info.plugins : [];

    // Resolve identifier and matched URL from input.
    let identifier = null;
    let matchedUrl = null;

    const parsedInput = parseGitHubUrl(nameOrUrl);
    if (parsedInput) {
        identifier = `${parsedInput.owner}-${parsedInput.repo}`;
        matchedUrl = plugins.find(u => {
            const p = parseGitHubUrl(u);
            return p && p.owner === parsedInput.owner && p.repo === parsedInput.repo;
        });
    } else {
        // Match by repo name against info.json plugins array.
        const lower = nameOrUrl.toLowerCase();
        const found = plugins.find(u => {
            const p = parseGitHubUrl(u);
            return p && (p.repo.toLowerCase() === lower || `${p.owner}-${p.repo}`.toLowerCase() === lower);
        });
        if (found) {
            const p = parseGitHubUrl(found);
            identifier = `${p.owner}-${p.repo}`;
            matchedUrl = found;
        }
    }

    // Fallback: match against existing cache directories.
    if (!identifier) {
        try {
            const dirs = fs.readdirSync(rwPluginsDir(state.root), { withFileTypes: true })
                .filter(e => e.isDirectory()).map(e => e.name);
            const lower = nameOrUrl.toLowerCase();
            const matched = dirs.find(d =>
                d.toLowerCase() === lower || d.toLowerCase().includes(lower)
            );
            if (matched) identifier = matched;
        } catch (_) {}
    }

    if (!identifier) {
        console.error(`Plugin '${nameOrUrl}' not found. Use 'rw list plugins' to see registered plugins.`);
        process.exit(1);
    }

    // Remove .rw/plugins/<id>/ cache.
    const cacheDir = path.join(rwPluginsDir(state.root), identifier);
    if (fs.existsSync(cacheDir)) {
        fs.rmSync(cacheDir, { recursive: true, force: true });
        console.log(`  \u2713 Removed .rw/plugins/${identifier}/`);
    } else {
        console.warn(`  \u26a0 Cache not found: .rw/plugins/${identifier}/`);
    }

    // Remove matching binaries from build/plugins/.
    const matchedParsed = parseGitHubUrl(matchedUrl || nameOrUrl);
    const repoName      = matchedParsed ? matchedParsed.repo : identifier;
    const buildPluginsDir = path.join(state.root, 'build', 'plugins');
    try {
        const files = fs.readdirSync(buildPluginsDir).filter(f =>
            SHARED_EXTS.some(ext => f.endsWith(ext)) &&
            f.toLowerCase().startsWith(repoName.toLowerCase())
        );
        for (const f of files) {
            fs.unlinkSync(path.join(buildPluginsDir, f));
            console.log(`  \u2713 Removed build/plugins/${f}`);
        }
    } catch (_) {}

    // Remove from info.json.
    if (matchedUrl) {
        info.plugins = plugins.filter(u => u !== matchedUrl);
        saveInfo(state.root, info);
        console.log(`  \u2713 Removed from info.json`);
    }

    console.log(`\nPlugin '${identifier}' removed.\n`);
}

// ─── Entry ────────────────────────────────────────────────────────────────────

function run(args) {
    const [type, ...rest] = (args || []);
    switch ((type || '').toLowerCase()) {
        case 'page':   return removePage(rest[0]);
        case 'plugin': return removePlugin(rest[0]);
        default:
            console.error('Usage: rw remove <page|plugin> [args]');
            console.error('  rw remove page <name>         Move page to .rw/trash/ and clean configuration');
            console.error('  rw remove plugin <name|url>   Remove cached and installed plugin');
            process.exit(1);
    }
}

module.exports = { run };
