#!/bin/sh
# Copyright (C) 2025 spur27
# SPDX-License-Identifier: BSL-1.0
#
# This file is part of RenWeb Engine.
#
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

EXES=""
for _f in "$SCRIPT_DIR"/@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*; do
    [ -f "$_f" ] && [ -x "$_f" ] && EXES="${EXES}${_f}
"
done

if [ -z "$EXES" ]; then
    echo "Error: No executables found matching @EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*"
    exit 1
fi

COUNT=$(printf '%s' "$EXES" | grep -c .)

if [ "$COUNT" -gt 1 ]; then
    ARCH_PARAM="$1"
    if [ -z "$ARCH_PARAM" ]; then
        echo "Error: Multiple executables found. Specify architecture:"
        printf '%s' "$EXES" | while IFS= read -r _exe; do
            printf '  %s\n' "${_exe##*-}"
        done
        printf 'Usage: %s <arch> [args...]\n' "$0"
        exit 1
    fi
    EXE="$SCRIPT_DIR/@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-$ARCH_PARAM"
    [ ! -x "$EXE" ] && echo "Error: No executable for arch: $ARCH_PARAM" && exit 1
    shift
else
    EXE=$(printf '%s' "$EXES" | head -n1)
fi

_rw_arch="${EXE##*-}"
if   [ -d "$SCRIPT_DIR/lib-${_rw_arch}" ]; then
    LIB_DIR="$SCRIPT_DIR/lib-${_rw_arch}"
elif [ -d "$SCRIPT_DIR/lib" ]; then
    LIB_DIR="$SCRIPT_DIR/lib"
else
    LIB_DIR="/lib"
    printf 'Warning: no bundled lib-%s/ or lib/ found; running against system libraries (no isolation)\n' "$_rw_arch" >&2
fi
unset _rw_arch

case "$(uname -s)" in
    Darwin) export DYLD_LIBRARY_PATH="$LIB_DIR:${DYLD_LIBRARY_PATH:-}" ;;
    *)      export LD_LIBRARY_PATH="$LIB_DIR:${LD_LIBRARY_PATH:-}" ;;
esac

unset LD_PRELOAD
export GST_PLUGIN_SYSTEM_PATH_1_0="$LIB_DIR/gstreamer-1.0"
export GST_PLUGIN_PATH=""
export GST_GL_PLATFORM=egl
export GDK_PIXBUF_MODULE_FILE="$LIB_DIR/gdk-pixbuf-2.0/loaders.cache"
export NO_AT_BRIDGE=1

export GIO_MODULE_DIR="$LIB_DIR/gio/modules"

_rw_musl=0
find /lib /usr/lib -maxdepth 2 -name 'ld-musl-*.so*' 2>/dev/null | grep -q . && _rw_musl=1
if [ "$_rw_musl" -eq 1 ]; then
    export GTK_MODULES=""
    export GTK_PATH=""
    export LIBGL_ALWAYS_SOFTWARE=1
    export LIBGL_DRIVERS_PATH="$LIB_DIR/dri"
    export GBM_BACKENDS_PATH="$LIB_DIR/gbm"
    export __EGL_VENDOR_LIBRARY_DIRS="$LIB_DIR/glvnd/egl_vendor.d"
fi
unset _rw_musl

_rw_wl_sock=""
case "${WAYLAND_DISPLAY:-}" in
    /*) _rw_wl_sock="$WAYLAND_DISPLAY" ;;
    ?*) _rw_wl_sock="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/$WAYLAND_DISPLAY" ;;
esac
if [ -n "$_rw_wl_sock" ] && [ -S "$_rw_wl_sock" ]; then
    export GDK_BACKEND=wayland
elif [ -n "${DISPLAY:-}" ]; then
    export GDK_BACKEND=x11
else
    export GDK_BACKEND=wayland
fi
unset _rw_wl_sock

export ENCHANT_CONFIG_DIR="$LIB_DIR/enchant"

_rw_fc_path=""
for _rw_d in /etc/fonts /usr/local/etc/fonts /usr/share/fontconfig; do
    [ -f "$_rw_d/fonts.conf" ] && { _rw_fc_path="$_rw_d"; break; }
done
[ -n "$_rw_fc_path" ] && export FONTCONFIG_PATH="$_rw_fc_path"
unset _rw_fc_path _rw_d

if [ -d "$LIB_DIR/webkit2gtk-4.1" ]; then
    export WEBKIT_EXEC_PATH="$LIB_DIR/webkit2gtk-4.1"
    export WEBKIT_INJECTED_BUNDLE_PATH="$LIB_DIR/webkit2gtk-4.1"
    _wk_dest="/usr/local/libexec/webkit2gtk-4.1"
    _wk_src="$LIB_DIR/webkit2gtk-4.1"
    if [ "$(readlink "$_wk_dest" 2>/dev/null)" != "$_wk_src" ]; then
        set +e
        mkdir -p /usr/local/libexec 2>/dev/null
        if [ -d "$_wk_dest" ] && [ ! -L "$_wk_dest" ]; then
            rm -rf "$_wk_dest" 2>/dev/null
            if [ -d "$_wk_dest" ]; then
                printf 'Warning: could not remove %s — run once with sudo to fix\n' "$_wk_dest" >&2
            fi
        fi
        ln -sfn "$_wk_src" "$_wk_dest" 2>/dev/null
        set -e
    fi
fi

BUNDLED_LD=""
for _ld in "$LIB_DIR"/ld-*.so*; do
    [ -f "$_ld" ] && [ -x "$_ld" ] && { BUNDLED_LD="$_ld"; break; }
done

if [ -n "$BUNDLED_LD" ]; then
    _rw_ld_hash=$(sha256sum "$BUNDLED_LD" 2>/dev/null | cut -c1-16)
    if [ -n "$_rw_ld_hash" ]; then
        mkdir -p /tmp/.renweb/.so 2>/dev/null || true
        chmod +t /tmp/.renweb/.so 2>/dev/null || true
        ln -sf "$BUNDLED_LD" "/tmp/.renweb/.so/${_rw_ld_hash}.so" 2>/dev/null || true
    fi
    unset _rw_ld_hash
fi
export RENWEB_EXECUTABLE_PATH="$EXE"
[ -n "$BUNDLED_LD" ] && exec "$BUNDLED_LD" --library-path "$LIB_DIR" "$EXE" "$@"
exec "$EXE" "$@"
