#!/bin/sh
# Copyright (C) 2025 spur27
# SPDX-License-Identifier: BSL-1.0
#
# This file is part of RenWeb Engine.
#
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Collect all matching executables (POSIX-compatible glob, no nullglob needed)
EXES=""
for _f in "$SCRIPT_DIR"/@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*; do
    [ -f "$_f" ] && [ -x "$_f" ] && EXES="${EXES}${_f}
"
done

if [ -z "$EXES" ]; then
    echo "Error: No executables found matching @EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*"
    exit 1
fi

COUNT=$(printf '%s' "$EXES" | grep -c .)

if [ "$COUNT" -gt 1 ]; then
    ARCH_PARAM="$1"
    if [ -z "$ARCH_PARAM" ]; then
        echo "Error: Multiple executables found. Specify architecture:"
        printf '%s' "$EXES" | while IFS= read -r _exe; do
            printf '  %s\n' "${_exe##*-}"
        done
        printf 'Usage: %s <arch> [args...]\n' "$0"
        exit 1
    fi
    EXE="$SCRIPT_DIR/@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-$ARCH_PARAM"
    [ ! -x "$EXE" ] && echo "Error: No executable for arch: $ARCH_PARAM" && exit 1
    shift
else
    EXE=$(printf '%s' "$EXES" | head -n1)
fi

LIB_DIR="$SCRIPT_DIR/lib"
[ ! -d "$LIB_DIR" ] && echo "Error: Library directory not found: lib" && exit 1

case "$(uname -s)" in
    Darwin) export DYLD_LIBRARY_PATH="$LIB_DIR:${DYLD_LIBRARY_PATH:-}" ;;
    *)      export LD_LIBRARY_PATH="$LIB_DIR:${LD_LIBRARY_PATH:-}" ;;
esac

# If a bundled dynamic linker is present, invoke it directly so that
# glibc-linked binaries run correctly on musl-based systems (e.g. Alpine).
BUNDLED_LD=""
for _ld in "$LIB_DIR"/ld-*.so*; do
    [ -f "$_ld" ] && [ -x "$_ld" ] && { BUNDLED_LD="$_ld"; break; }
done
[ -n "$BUNDLED_LD" ] && exec "$BUNDLED_LD" --library-path "$LIB_DIR" "$EXE" "$@"
exec "$EXE" "$@"
