:: Copyright (C) 2025 spur27
:: SPDX-License-Identifier: BSL-1.0
::
:: This file is part of RenWeb Engine.
::
:: Boost Software License - Version 1.0 - August 17th, 2003
::
:: Permission is hereby granted, free of charge, to any person or organization
:: obtaining a copy of the software and accompanying documentation covered by
:: this license (the "Software") to use, reproduce, display, distribute,
:: execute, and transmit the Software, and to prepare derivative works of the
:: Software, and to permit third-parties to whom the Software is furnished to
:: do so, all subject to the following:
::
:: The copyright notices in the Software and this entire statement, including
:: the above license grant, this restriction and the following disclaimer,
:: must be included in all copies of the Software, in whole or in part, and
:: all derivative works of the Software, unless such copies or derivative
:: works are solely in the form of machine-executable object code generated by
:: a source language processor.
::
:: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
:: IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
:: FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
:: SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
:: FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
:: ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
:: DEALINGS IN THE SOFTWARE.
@echo off
setlocal enabledelayedexpansion
set "SCRIPT_DIR=%~dp0"
set "PATTERN=@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*.exe"
set "ARCH_PARAM=%~1"
set "COUNT=0"
for %%F in ("%SCRIPT_DIR%!PATTERN!") do set /a COUNT+=1
if !COUNT! equ 0 (echo Error: No executables found matching !PATTERN! & exit /b 1)
if !COUNT! gtr 1 (
    if "!ARCH_PARAM!"=="" (
        echo Error: Multiple executables found. Specify architecture:
        for %%F in ("%SCRIPT_DIR%!PATTERN!") do (
            set "FNAME=%%~nF"
            for /f "tokens=* delims=-" %%A in ("!FNAME:*-=!") do set "ARCH=%%A"
            echo   !ARCH!
        )
        echo Usage: %~nx0 ^<arch^> [args...]
        exit /b 1
    )
    set "EXE=%SCRIPT_DIR%@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-!ARCH_PARAM!.exe"
    if not exist "!EXE!" (echo Error: No executable for arch: !ARCH_PARAM! & exit /b 1)
    shift
) else (
    for %%F in ("%SCRIPT_DIR%!PATTERN!") do set "EXE=%%F"
)
for %%F in ("!EXE!") do set "FNAME=%%~nF"
set "LIB_DIR=%SCRIPT_DIR%lib"
if not exist "!LIB_DIR!" (echo Error: Library directory not found: lib & exit /b 1)
if exist "!LIB_DIR!\WebView2Runtime" set "WEBVIEW2_BROWSER_EXECUTABLE_FOLDER=!LIB_DIR!\WebView2Runtime"
set "PATH=!LIB_DIR!;%PATH%"
"!EXE!" %*
