:: Copyright (C) 2025 spur27
:: SPDX-License-Identifier: BSL-1.0
::
:: This file is part of RenWeb Engine.
::
:: Boost Software License - Version 1.0 - August 17th, 2003
::
:: Permission is hereby granted, free of charge, to any person or organization
:: obtaining a copy of the software and accompanying documentation covered by
:: this license (the "Software") to use, reproduce, display, distribute,
:: execute, and transmit the Software, and to prepare derivative works of the
:: Software, and to permit third-parties to whom the Software is furnished to
:: do so, all subject to the following:
::
:: The copyright notices in the Software and this entire statement, including
:: the above license grant, this restriction and the following disclaimer,
:: must be included in all copies of the Software, in whole or in part, and
:: all derivative works of the Software, unless such copies or derivative
:: works are solely in the form of machine-executable object code generated by
:: a source language processor.
::
:: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
:: IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
:: FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
:: SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
:: FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
:: ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
:: DEALINGS IN THE SOFTWARE.
@echo off
setlocal enabledelayedexpansion
set "SCRIPT_DIR=%~dp0"
set "PATTERN=@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-*.exe"
set "ARCH_PARAM=%~1"
set "COUNT=0"
for %%F in ("%SCRIPT_DIR%!PATTERN!") do set /a COUNT+=1
if !COUNT! equ 0 (echo Error: No executables found matching !PATTERN! & exit /b 1)
if !COUNT! gtr 1 (
    if "!ARCH_PARAM!"=="" (
        echo Error: Multiple executables found. Specify architecture:
        for %%F in ("%SCRIPT_DIR%!PATTERN!") do (
            set "FNAME=%%~nF"
            for /f "tokens=* delims=-" %%A in ("!FNAME:*-=!") do set "ARCH=%%A"
            echo   !ARCH!
        )
        echo Usage: %~nx0 ^<arch^> [args...]
        exit /b 1
    )
    set "EXE=%SCRIPT_DIR%@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-!ARCH_PARAM!.exe"
    if not exist "!EXE!" (echo Error: No executable for arch: !ARCH_PARAM! & exit /b 1)
    shift
) else (
    for %%F in ("%SCRIPT_DIR%!PATTERN!") do set "EXE=%%F"
)
for %%F in ("!EXE!") do set "FNAME=%%~nF"
set "EXE_ARCH=!FNAME:@EXE_NAME@-@EXE_VERSION@-@OS_NAME@-=!"
set "LIB_DIR="
if exist "%SCRIPT_DIR%lib-!EXE_ARCH!" (set "LIB_DIR=%SCRIPT_DIR%lib-!EXE_ARCH!")
if "!LIB_DIR!"=="" if exist "%SCRIPT_DIR%lib" (set "LIB_DIR=%SCRIPT_DIR%lib")
if "!LIB_DIR!"=="" (
    echo Warning: No lib-!EXE_ARCH! or lib directory found. Using system library paths only.
) else (
    set "WV2_INSTALLED=0"
    for /f "tokens=3" %%v in ('reg query "HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" /v "pv" 2^>nul') do (
        if not "%%v"=="0.0.0.0" set "WV2_INSTALLED=1"
    )
    if "!WV2_INSTALLED!"=="0" (
        for /f "tokens=3" %%v in ('reg query "HKCU\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" /v "pv" 2^>nul') do (
            if not "%%v"=="0.0.0.0" set "WV2_INSTALLED=1"
        )
    )
    if "!WV2_INSTALLED!"=="0" (
        set "BOOTSTRAP_FOUND=0"
        for %%f in ("!LIB_DIR!\MicrosoftEdgeWebview2Setup*.exe") do (
            set "BOOTSTRAP_FOUND=1"
            echo WebView2 runtime not found. Installing via bootstrapper...
            "%%f" /silent /install
            echo Installation complete. Bootstrapper retained for future updates.
        )
        if "!BOOTSTRAP_FOUND!"=="0" (
            echo Warning: WebView2 runtime not detected and no bootstrapper found in !LIB_DIR!.
        )
    )
    set "PATH=!LIB_DIR!;%PATH%"
)
"!EXE!" %*
