'use strict';

const { toSnake } = require('../utils');
const { DEFAULT_PERMISSIONS } = require('../constants');


const DEFAULT_TEMPLATE_INFO = {
    title:          'My RenWeb App',
    description:    '',
    author:         '',
    version:        '0.0.1',
    license:        'BSL 1.0',
    categories:     ['Utility'],
    app_id:         'io.github.user.my_renweb_app',
    repository:     '',
    starting_pages: ['main'],
    permissions:    { ...DEFAULT_PERMISSIONS },
    origins:        [],
};


function makeCopilotInstructions(info, pageName) {
    const fence = '```';
    return [
        `# ${info.title} — Copilot Instructions`,
        '',
        'This project is a **RenWeb** desktop application. RenWeb is a cross-platform',
        'framework for building native GUI apps with an HTML/CSS/JS frontend and a',
        'C++ backend. The engine is a sub-2 MB native executable with no Chromium',
        'dependency.',
        '',
        '## JS API (`window.renweb`)',
        '',
        'The engine injects `window.renweb` into every page at startup.',
        '',
        '| Namespace | Purpose |',
        '|-----------|---------|',
        '| `renweb.window`   | Resize, focus, minimize, maximize, set title / opacity |',
        '| `renweb.log`      | Structured logging → spdlog (trace / debug / info / warn / error) |',
        '| `renweb.fs`       | Read, write, list files and directories |',
        '| `renweb.config`   | Read / write window config properties at runtime |',
        '| `renweb.system`   | Clipboard, shell exec, open URL, system info |',
        '| `renweb.process`  | Spawn additional windows, manage child processes |',
        '| `renweb.navigate` | Navigate to a different page |',
        '| `renweb.network`  | HTTP requests and WebSocket from JS |',
        '| `renweb.debug`    | Developer utilities |',
        '| `renweb.plugins`  | Call functions exported by loaded native plugins |',
        '',
        'Full API reference: https://spur27.github.io/RenWeb-Engine/?page=api',
        '',
        '## Architecture',
        '',
        '- The engine serves web content from `build/content/<page>/` via an embedded',
        '  HTTP server bound to `127.0.0.1`.',
        '- `info.json` (project root) controls app metadata; `config.json` controls',
        '  window properties. Both are copied to `build/` at setup time.',
        '- Plugins are shared libraries (`.so`/`.dll`/`.dylib`) in `build/plugins/` —',
        '  they extend the JS API without modifying the engine.',
        '',
        '## Project Structure',
        '',
        fence,
        `${toSnake(info.title)}/`,
        '├── .github/',
        '│   └── copilot-instructions.md   ← this file',
        '├── licenses/                     ← engine dependency licences',
        '├── resource/                     ← platform resources (manifests, icons)',
        '├── credentials/                  ← credential documentation template',
        '├── src/',
        '│   ├── content/',
        `│   │   └── ${pageName}/          ← page HTML, CSS, JS`,
        '│   ├── assets/                   ← shared images, fonts, audio',
        '│   └── modules/                  ← shared JS modules',
        '│       └── renweb/               ← RenWeb JS API',
        '├── build/                        ← generated by rw build (git-ignored)',
        '│   ├── renweb-<exe>              ← engine executable (platform + arch specific)',
        '│   ├── info.json',
        '│   ├── config.json',
        '│   └── content/',
        `│       └── ${pageName}/          ← served web content (starting page)`,
        '├── info.json                     ← project metadata',
        '├── config.json                   ← window configuration',
        '└── .gitignore',
        fence,
        '',
    ].join('\n');
}


function makeConfigJson(info, pageName) {
    return JSON.stringify({
        __defaults__: {
            title_bar:    true,
            fullscreen:   false,
            keepabove:    false,
            maximize:     false,
            minimize:     false,
            opacity:      1,
            position:     { x: 0, y: 0 },
            resizable:    true,
            size:         { width: 1280, height: 840 },
            taskbar_show: true,
            initially_shown: true,
        },
        [pageName]: { title: info.title, merge_defaults: true },
    }, null, 4);
}

function makeInfoJson(info, pageName) {
    return JSON.stringify({
        title:          info.title,
        description:    info.description,
        author:         info.author,
        version:        info.version,
        license:        info.license,
        categories:     info.categories,
        app_id:         info.app_id,
        repository:     info.repository,
        starting_pages: [pageName],
        permissions:    { ...DEFAULT_PERMISSIONS },
        origins:        [],
    }, null, 4);
}


function makeViteConfig(type, pageName) {
    const plugins = {
        react:  `import react from '@vitejs/plugin-react';\n\nconst plugins = [react()];`,
        vue:    `import vue   from '@vitejs/plugin-vue';\n\nconst plugins = [vue()];`,
        svelte: `import { svelte } from '@sveltejs/vite-plugin-svelte';\n\nconst plugins = [svelte()];`,
        preact: `import preact from '@preact/preset-vite';\n\nconst plugins = [preact()];`,
    }[type] || 'const plugins = [];';

    return `import { defineConfig } from 'vite';
${plugins}

// RenWeb: output into build/content/${pageName}/ so the engine can load it.
// base './' ensures all asset paths are relative (required for file:// loading).
export default defineConfig({
  plugins,
  base: './',
  build: {
    outDir: './build/content/${pageName}',
    emptyOutDir: true,
  },
});
`;
}

module.exports = {
    DEFAULT_TEMPLATE_INFO,
    makeCopilotInstructions,
    makeConfigJson,
    makeInfoJson,
    makeViteConfig,
};
