// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
/// <reference path="./index.d.ts" />
import {
    Log, 
    Window,
    Config,
    Debug,
    FS,
    System,
    Properties
 } from './index.js';

window.renweb.onReady = async () => {
    const os = String(await System.getOS()).toLowerCase();
    let targetOpacity = 1;
    if (os === "macos") {
        targetOpacity = await Properties.getOpacity();
        await Properties.setOpacity(0);
    }

    await Window.show(true);

    if (os === "macos") {
        const fadeSteps = 5;
        const stepDelayMs = 10;
        for (let i = 1; i <= fadeSteps; i++) {
            await new Promise((resolve) => setTimeout(resolve, stepDelayMs));
            await Properties.setOpacity((targetOpacity * i) / fadeSteps);
        }
    }
}

function updateTestStatus(testId, status) {
    const testItem = document.getElementById(testId);
    if (!testItem) return;
    
    testItem.className = `test-item ${status}`;
    const statusSpan = testItem.querySelector('.status');
    if (statusSpan) {
        const statusText = statusSpan.textContent;
        if (statusText !== 'MANUAL') {
            statusSpan.className = `status ${status}`;
            statusSpan.textContent = status.toUpperCase();
        }
    }
}

function testImage(imgId, resultId, testId, isWhitelisted) {
    const img = document.getElementById(imgId);
    const resultEl = document.getElementById(resultId);
    if (!img || !resultEl) return;
    
    let handled = false;
    
    const checkImage = () => {
        if (handled) return;
        handled = true;
        
        if (img.complete) {
            if (img.naturalWidth > 0) {
                if (isWhitelisted) {
                    resultEl.textContent = '✓ Successfully loaded from whitelisted origin';
                    updateTestStatus(testId, 'pass');
                } else {
                    resultEl.textContent = '✗ Loaded (origin blocking not working!)';
                    updateTestStatus(testId, 'fail');
                }
            } else {
                if (isWhitelisted) {
                    resultEl.textContent = '✗ Failed to load (unexpected)';
                    updateTestStatus(testId, 'fail');
                } else {
                    resultEl.textContent = '✓ Blocked by origin filter (expected)';
                    updateTestStatus(testId, 'pass');
                }
            }
        }
    };
    
    img.addEventListener('load', checkImage);
    img.addEventListener('error', checkImage);
    
    // Timeout fallback - check after 3 seconds
    setTimeout(() => {
        if (!handled) {
            checkImage();
        }
    }, 3000);
    
    // Check immediately if already complete
    if (img.complete) {
        checkImage();
    }
}

async function runTrustTests() {
    // Test 1: Log call — bypasses trust gate, must always succeed
    try {
        await Log.debug('[security-test] trust gate log probe');
        document.getElementById('result-bind-log').textContent = '✓ Log call succeeded (trust-gate bypass confirmed)';
        updateTestStatus('test-bind-log', 'pass');
    } catch (e) {
        document.getElementById('result-bind-log').textContent = `✗ Log call failed: ${e.message}`;
        updateTestStatus('test-bind-log', 'fail');
    }

    // Test 2: Window.currentPage — trust-gated
    try {
        const page = await Window.currentPage();
        document.getElementById('result-bind-current-page').textContent = `✓ Got page name: "${page}"`;
        updateTestStatus('test-bind-current-page', 'pass');
    } catch (e) {
        document.getElementById('result-bind-current-page').textContent = `✗ Blocked or failed: ${e.message}`;
        updateTestStatus('test-bind-current-page', 'fail');
    }

    // Test 3: Window.currentTitle — trust-gated
    try {
        const title = await Window.currentTitle();
        document.getElementById('result-bind-get-title').textContent = `✓ Got title: "${title}"`;
        updateTestStatus('test-bind-get-title', 'pass');
    } catch (e) {
        document.getElementById('result-bind-get-title').textContent = `✗ Blocked or failed: ${e.message}`;
        updateTestStatus('test-bind-get-title', 'fail');
    }

    // Test 4: Config.getConfig — trust-gated
    try {
        const cfg = await Config.getConfig();
        const val = cfg != null ? cfg['resizable'] : undefined;
        document.getElementById('result-bind-config-get').textContent = `✓ Config read succeeded: resizable = ${JSON.stringify(val)}`;
        updateTestStatus('test-bind-config-get', 'pass');
    } catch (e) {
        document.getElementById('result-bind-config-get').textContent = `✗ Blocked or failed: ${e.message}`;
        updateTestStatus('test-bind-config-get', 'fail');
    }

    // Test 5: FS.exists — trust-gated filesystem call
    try {
        const exists = await FS.exists('./info.json');
        document.getElementById('result-bind-filesystem').textContent = `✓ FS call succeeded: info.json exists = ${exists}`;
        updateTestStatus('test-bind-filesystem', 'pass');
    } catch (e) {
        document.getElementById('result-bind-filesystem').textContent = `✗ Blocked or failed: ${e.message}`;
        updateTestStatus('test-bind-filesystem', 'fail');
    }

    // Test 6: Verify current page name is "security" — the trusted rule key
    try {
        const page = await Window.currentPage();
        const isSecurity = page === 'security';
        const resultEl = document.getElementById('result-trust-page-name');
        if (isSecurity) {
            resultEl.textContent = `✓ Current page is "${page}" — add "!security" to trusted array in info.json to block this page's native calls`;
            updateTestStatus('test-trust-page-name', 'pass');
        } else {
            resultEl.textContent = `⚠ Current page is "${page}", expected "security" — rule matching may not behave as documented`;
            updateTestStatus('test-trust-page-name', 'pending');
        }
    } catch (e) {
        document.getElementById('result-trust-page-name').textContent = `✗ Could not determine page: ${e.message}`;
        updateTestStatus('test-trust-page-name', 'fail');
    }
}

function runTests() {
    console.log('Starting origin security tests...');

    runTrustTests().catch(e => console.error('Trust tests error:', e));

    // Test: Google Image (whitelisted)
    testImage('google-img', 'result-img-google', 'test-img-google', true);
    
    // Test: Placeholder Image (non-whitelisted, should be blocked)
    testImage('placeholder-img', 'result-img-placeholder', 'test-img-placeholder', false);
    
    // Test: Unsplash Image (non-whitelisted, should be blocked)
    testImage('unsplash-img', 'result-img-unsplash', 'test-img-unsplash', false);
    
    // Test: Data URI (should work - internal protocol)
    testImage('data-img', 'result-data-uri', 'test-data-uri', true);

    // Test: External script (jQuery from CDN - should be blocked)
    setTimeout(() => {
        if (typeof jQuery !== 'undefined' || typeof $ !== 'undefined') {
            document.getElementById('result-script-external').textContent = '✗ jQuery loaded (origin blocking not working!)';
            updateTestStatus('test-script-external', 'fail');
        } else {
            document.getElementById('result-script-external').textContent = '✓ External script blocked (expected)';
            updateTestStatus('test-script-external', 'pass');
        }
    }, 2000);

    // Test: Fetch from Google (whitelisted) with timeout
    const fetchGoogleTimeout = setTimeout(() => {
        document.getElementById('result-fetch-google').textContent = '⏱ Request timed out (may be blocked or slow network)';
        updateTestStatus('test-fetch-google', 'pending');
    }, 5000);
    
    fetch('https://www.google.com', { mode: 'no-cors' })
        .then(response => {
            clearTimeout(fetchGoogleTimeout);
            document.getElementById('result-fetch-google').textContent = '✓ Successfully connected to whitelisted origin';
            updateTestStatus('test-fetch-google', 'pass');
        })
        .catch(e => {
            clearTimeout(fetchGoogleTimeout);
            document.getElementById('result-fetch-google').textContent = `✗ Failed: ${e.message}`;
            updateTestStatus('test-fetch-google', 'fail');
        });

    // Test: Fetch from GitHub API (non-whitelisted, should be blocked) with timeout
    const fetchGithubTimeout = setTimeout(() => {
        document.getElementById('result-fetch-github').textContent = '✓ Request blocked or timed out (expected)';
        updateTestStatus('test-fetch-github', 'pass');
    }, 5000);
    
    fetch('https://api.github.com')
        .then(response => {
            clearTimeout(fetchGithubTimeout);
            document.getElementById('result-fetch-github').textContent = '✗ Connected (origin blocking not working!)';
            updateTestStatus('test-fetch-github', 'fail');
        })
        .catch(e => {
            clearTimeout(fetchGithubTimeout);
            document.getElementById('result-fetch-github').textContent = `✓ Blocked: ${e.message}`;
            updateTestStatus('test-fetch-github', 'pass');
        });

    // Test: Fetch from JSONPlaceholder (non-whitelisted, should be blocked) with timeout
    const fetchJsonTimeout = setTimeout(() => {
        document.getElementById('result-fetch-jsonplaceholder').textContent = '✓ Request blocked or timed out (expected)';
        updateTestStatus('test-fetch-jsonplaceholder', 'pass');
    }, 5000);
    
    fetch('https://jsonplaceholder.typicode.com/posts/1')
        .then(response => {
            clearTimeout(fetchJsonTimeout);
            document.getElementById('result-fetch-jsonplaceholder').textContent = '✗ Connected (origin blocking not working!)';
            updateTestStatus('test-fetch-jsonplaceholder', 'fail');
        })
        .catch(e => {
            clearTimeout(fetchJsonTimeout);
            document.getElementById('result-fetch-jsonplaceholder').textContent = `✓ Blocked: ${e.message}`;
            updateTestStatus('test-fetch-jsonplaceholder', 'pass');
        });

    // Test: iFrame from example.com (non-whitelisted, should be blocked)
    setTimeout(() => {
        const exampleFrame = document.getElementById('example-frame');
        const resultEl = document.getElementById('result-iframe-example');
        if (exampleFrame && resultEl) {
            try {
                // Check if iframe loaded by attempting to access its location
                const src = exampleFrame.src;
                const srcLoaded = exampleFrame.contentWindow && exampleFrame.contentWindow.length !== undefined;
                
                // If we can access contentWindow, frame might have loaded (but cross-origin prevents access)
                // Check if frame actually has content loaded
                if (srcLoaded) {
                    resultEl.textContent = '⚠ iFrame element exists (cross-origin prevents verification)';
                    updateTestStatus('test-iframe-example', 'pending');
                } else {
                    resultEl.textContent = '✓ iFrame blocked (expected)';
                    updateTestStatus('test-iframe-example', 'pass');
                }
            } catch (e) {
                // Exception thrown = cross-origin block or load failure
                resultEl.textContent = '✓ iFrame blocked or restricted (expected)';
                updateTestStatus('test-iframe-example', 'pass');
            }
        }
    }, 3000);

    // Test: WebServer resources
    updateTestStatus('test-webserver', 'pass');

    console.log('Origin security tests initialized');
}

// Run tests when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', runTests);
} else {
    runTests();
}

// Event listeners for keyboard shortcuts
document.addEventListener("keydown", async (e) => {
    if (e.ctrlKey) {
        if (e.key === 'q') {
            await Log.debug("CTRL + q was pressed.");
            await Window.terminate();
            return;
        } else if (e.key === 'r') {
            await Log.debug("CTRL + r was pressed.");
            await Window.reloadPage();
            return;
        } else if (e.key === 's') {
            await Log.debug("CTRL + s was pressed.");
            await Config.saveConfig();
            return;
        } else if (e.key === 'i') {
            await Log.debug("CTRL + i was pressed.");
            await Debug.openDevtools();
        }
    }
});

// Prevent trackpad horizontal swipe navigation
document.addEventListener("wheel", (e) => {
    // Prevent horizontal scrolling that triggers browser navigation
    if (Math.abs(e.deltaX) > Math.abs(e.deltaY)) {
        e.preventDefault();
    }
}, { passive: false });

// Additional prevention for touchpad gestures
window.addEventListener("touchstart", (e) => {
    if (e.touches.length > 1) {
        e.preventDefault();
    }
}, { passive: false });

window.addEventListener("touchmove", (e) => {
    if (e.touches.length > 1) {
        e.preventDefault();
    }
}, { passive: false });

// Window onload event - show window after content loaded
window.addEventListener('load', async () => {
});

// Back button
document.querySelector('.back-button')?.addEventListener('click', async () => {
    try {
        await Window.navigatePage('test');
    } catch (e) {
        await Log.error(e.message);
    }
});
