// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
/// <reference path="./index.d.ts" />
import {
    Log, 
    Window,
    System,
    Properties
 } from './index.js';

window.renweb.onReady = async () => {
    const os = String(await System.getOS()).toLowerCase();
    let targetOpacity = 1;
    if (os === "macos") {
        targetOpacity = await Properties.getOpacity();
        await Properties.setOpacity(0);
    }

    await Window.show(true);

    if (os === "macos") {
        const fadeSteps = 5;
        const stepDelayMs = 10;
        for (let i = 1; i <= fadeSteps; i++) {
            await new Promise((resolve) => setTimeout(resolve, stepDelayMs));
            await Properties.setOpacity((targetOpacity * i) / fadeSteps);
        }
    }
    await Window.focus();
}

// Back button
document.querySelector('.back-button')?.addEventListener('click', async () => {
    try {
        await Window.navigatePage('test');
    } catch (e) {
        await Log.error(e.message);
    }
});
