// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <memory>
#include <boost/version.hpp>
#include <boost/json.hpp>
#include "file.hpp"
#include "interfaces/Ilogger.hpp"

#ifndef RENWEB_EXPECTED_BOOST_VERSION
#define RENWEB_EXPECTED_BOOST_VERSION 109000
#endif

static_assert(
    BOOST_VERSION == RENWEB_EXPECTED_BOOST_VERSION,
    "Boost version mismatch: RenWeb expects Boost 1.90.0 (BOOST_VERSION=109000)."
);

using File = RenWeb::File;
using ILogger = RenWeb::ILogger;
namespace json = boost::json;

namespace RenWeb {
    class JSON {
        protected:
            std::shared_ptr<ILogger> logger;
            json::value json_data;
        public:
            std::shared_ptr<File> file;

            JSON(std::shared_ptr<ILogger> logger, std::shared_ptr<File> file);
            virtual ~JSON() = default;
            JSON(const JSON&) = delete;
            JSON& operator=(const JSON&) = delete;
            JSON(JSON&&) = default;
            JSON& operator=(JSON&&) = default;

            static json::value peek(File* file, const std::string& key);
            static json::object merge(json::object old_data, const json::object& new_data);
            virtual const json::value& getJson() const;
            virtual json::value getProperty(const std::string& key) const;
            virtual void setProperty(const std::string& key, const json::value& value);
            virtual void update(const json::object& new_data);
    };
};