// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include "info.hpp"
#include "interfaces/Ilogger.hpp"
#include "file.hpp"
#include "json.hpp"
#include "locate.hpp"
#include "spdlog/common.h"
#include "spdlog/logger.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/stdout_color_sinks.h"
#include "spdlog/sinks/stdout_sinks.h"
#include <cstdlib>
#include <iostream>
#include <memory>
#include <filesystem>

namespace RenWeb {
    struct LogFlags {
        bool log_silent = false;
        spdlog::level::level_enum log_level = spdlog::level::trace;
        bool log_clear = false;
        bool log_boring = false;
    };
    class FakeLogger : public RenWeb::ILogger {
        public:
            ~FakeLogger() override = default;
            void trace(const std::string& msg) override { (void)msg; };
            void debug(const std::string& msg) override { (void)msg; };
            void info(const std::string& msg) override { (void)msg; };
            void warn(const std::string& msg) override { (void)msg; };
            void error(const std::string& msg) override { (void)msg; };
            void critical(const std::string& msg) override { (void)msg; };
            void refresh(std::map<std::string, std::string> fmt) override { (void)fmt; };
    };
    class Logger : public RenWeb::ILogger {
        private: 
            std::unique_ptr<struct RenWeb::LogFlags> flags;
            std::unique_ptr<spdlog::logger> logger;
            std::shared_ptr<File> file;
            bool unable_to_log_msg = false;
        public:
            Logger(
                std::unique_ptr<LogFlags> flags = std::make_unique<LogFlags>()
            )
            : flags(std::move(flags))
            { 
                this->file = std::make_shared<File>(Locate::currentDirectory() / "log.txt");
                if (this->flags->log_clear) {
                    this->file->clear();
                }
                this->refresh({});
            };
            Logger(
                std::shared_ptr<File> file,
                std::unique_ptr<LogFlags> flags = std::make_unique<LogFlags>()
            )
            : flags(std::move(flags)),
              file(file)
            { 
                if (this->flags->log_clear) {
                    this->file->clear();
                }
                this->refresh({});
            };
            ~Logger() override = default;
            
            void trace(const std::string& msg) override {
                this->logger->trace(msg);
            }
            void debug(const std::string& msg) override {
                this->logger->debug(msg);
            };
            void info(const std::string& msg) override {
                this->logger->info(msg);
            };
            void warn(const std::string& msg) override {
                this->logger->warn(msg);
            };
            void error(const std::string& msg) override {
                this->logger->error(msg);
            };
            void critical(const std::string& msg) override {
                this->logger->critical(msg);
            };
            void refresh(std::map<std::string, std::string> fmt) override {
                const std::string date_str = "%Y-%m-%d %H:%M:%S.%e";
                const std::string thread_str = "%t";
                const std::string log_type_str = "%^%l%$";
                const std::string msg_str = "%v";
                const std::string page = (fmt.find("page") != fmt.end()) ? fmt.at("page") : "";
                std::stringstream colored_log_str, boring_log_str;
                if (!page.empty()) {
                    colored_log_str << "[\x1b[35m" << page << "\x1b[0m] ";
                    boring_log_str << "[" << page << "] ";
                }
                colored_log_str << "\x1b[34m" << date_str << "\x1b[0m"
                            << " [\x1b[3m" << thread_str << "\x1b[0m] "
                            << "[" << log_type_str << "] "
                            << msg_str;
                boring_log_str << date_str
                            << " [" << thread_str << "] "
                            << "[" << log_type_str << "] "
                            << msg_str;
                const std::string& console_pattern = this->flags->log_boring ? boring_log_str.str() : colored_log_str.str();
#if defined(_WIN32)
                spdlog::sink_ptr console_sink;
                if (this->flags->log_boring) {
                    console_sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();
                } else {
                    console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
                }
#else
                spdlog::sink_ptr console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
#endif
                console_sink->set_level(this->flags->log_level);
                console_sink->set_pattern(console_pattern);

                spdlog::sink_ptr file_sink;
                try {
                    file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(this->file->getPath().string(), false);
                } catch (const spdlog::spdlog_ex&) {
                    if (!this->unable_to_log_msg) {
                        if (this->flags->log_boring) {
                            std::cerr
                                << "[ERROR] [logger] Cannot write to: "
                                << this->file->getPath().string() << "\n"
                                << "[ERROR] [logger] RenWeb requires write access to its installation directory.\n"
                                << "[ERROR] [logger] Please reinstall RenWeb to a location where your user has write permissions\n"
                                << "[ERROR] [logger] (e.g. ~/renweb or /usr/local/renweb instead of a read-only /opt).\n";
                        } else if (!this->flags->log_silent) {
                            std::cerr
                                << "\033[31m[ERROR]\033[0m [logger] Cannot write to: "
                                << this->file->getPath().string() << "\n"
                                << "\033[31m[ERROR]\033[0m [logger] RenWeb requires write access to its installation directory.\n"
                                << "\033[31m[ERROR]\033[0m [logger] Please reinstall RenWeb to a location where your user has write permissions\n"
                                << "\033[31m[ERROR]\033[0m [logger] (e.g. ~/renweb or /usr/local/renweb instead of a read-only /opt).\n";
                        }
                        this->unable_to_log_msg = true;
                    }
                }
                std::vector<spdlog::sink_ptr> log_sinks;
                if (!this->flags->log_silent) {
                    log_sinks.push_back(console_sink);
                }
                if (file_sink) {
                    file_sink->set_level(spdlog::level::trace);
                    file_sink->set_pattern(boring_log_str.str());
                    log_sinks.push_back(file_sink);
                }

                this->logger.reset(new spdlog::logger("default", begin(log_sinks), end(log_sinks)));
                this->logger->set_level(spdlog::level::trace);
                if (this->flags->log_level < spdlog::level::info) {
                    this->logger->flush_on(spdlog::level::trace);
                } else {
                    this->logger->flush_on(spdlog::level::err);
                }
            };
    };
}

// Commented out to avoid namespace conflicts with cpp-httplib
// using Logger = RenWeb::Logger;
