// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <boost/json.hpp>
#include "interfaces/Ilogger.hpp"
#define MAX_NUM_PORTS_TO_TRY 64
#define BUFFER_SIZE 16 * 1024

#include <httplib.h>
#include "managers/callback_manager.hpp"
#include "interfaces/Iweb_server.hpp"
#include <filesystem>
#include <memory>

namespace RenWeb {
    class App;
}

namespace json = boost::json;

namespace RenWeb {
    class WebServer: public RenWeb::IWebServer {
        public:
            static std::string generateErrorHTML(int status_code, const std::string& status_message, const std::string& description = "");

            WebServer(
                std::shared_ptr<ILogger> logger,
                App* app
            );
            ~WebServer() override;
            std::string getURL() const override;
            void start() override;
            void stop() override;
            bool isURI(const std::string& uri) const override;            
            const std::vector<json::value>& getMessages() const override;
            void sendMessage(const std::string& ip, const json::value& message, time_t timeout_s, time_t timeout_ms) const override;
            json::object whoAreYou(const std::string& ip, time_t timeout_s, time_t timeout_ms) const override;
        private: 
            std::shared_ptr<ILogger> logger;
            App* app;
            std::filesystem::path base_path;
            std::unique_ptr<RenWeb::CallbackManager<std::string, void, const httplib::Request&, httplib::Response&>> method_callbacks;
            std::unique_ptr<httplib::Server> server;
            std::thread server_thread;
            unsigned short port = 0;
            const std::string ip = "127.0.0.1";
            std::vector<json::value> messages{};
            
            void setHandles();
            void setMethodCallbacks();
            void sendFile(
                const httplib::Request& req, 
                httplib::Response& res,
                const std::filesystem::path& path
            );
            void sendStatus(
                const httplib::Request& req, 
                httplib::Response& res, 
                const httplib::StatusCode& code,
                const std::string& desc =""
            );
            std::string getMimeType(const std::filesystem::path& file);
            static std::map<std::string, std::string> mime_types;            
    };
}