// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#pragma once

#include <boost/json/value.hpp>
#include <filesystem>
#include <functional>
#include <memory>
#include "file.hpp"
#include "config.hpp"
#include "logger.hpp"
#include "managers/in_out_manager.hpp"
#include "managers/callback_manager.hpp"

using File = RenWeb::File;
using Config = RenWeb::Config;
namespace json = boost::json;
using IOM = RenWeb::InOutManager<std::string, json::value, const json::value&>;
using CM = RenWeb::CallbackManager<std::string, json::value, const json::value&>;

namespace RenWeb {
   class App;
}

namespace RenWeb {
    class WindowFunctions {
        private:
            std::shared_ptr<ILogger> logger;
            RenWeb::App* app;
            std::map<std::string, json::value> saved_states;
            std::unique_ptr<CM> internal_callbacks;

            json::value formatOutput(const json::value& output);
            json::value formatOutput(const std::string& output);
            template<typename T>
                json::value formatOutput(const T& output);
            json::value processInput(const std::string& input);
            json::value processInput(const json::value& input);
            json::value processInput(const json::object& input);
            json::value processInput(const json::array& input);
            json::value getSingleParameter(const json::value& param);

            WindowFunctions* bindDefaults();
         /* Exposed-API function setters */
            WindowFunctions* setGetSets();
            WindowFunctions* setWindowCallbacks();
            WindowFunctions* setLogCallbacks();
            WindowFunctions* setFileSystemCallbacks();
            WindowFunctions* setConfigCallbacks();
            WindowFunctions* setSystemCallbacks();
            WindowFunctions* setProcessCallbacks();
            WindowFunctions* setDebugCallbacks();
            WindowFunctions* setNetworkCallbacks();
            WindowFunctions* setNavigateCallbacks();
            WindowFunctions* setPluginCallbacks();
         /* Hidden-API function setters*/
            WindowFunctions* setInternalCallbacks();
            
        public:
            std::unique_ptr<IOM> getsets;
            std::unique_ptr<CM> window_callbacks;
            std::unique_ptr<CM> log_callbacks;
            std::unique_ptr<CM> filesystem_callbacks;
            std::unique_ptr<CM> config_callbacks;
            std::unique_ptr<CM> system_callbacks;
            std::unique_ptr<CM> process_callbacks;
            std::unique_ptr<CM> debug_callbacks;
            std::unique_ptr<CM> network_callbacks;
            std::unique_ptr<CM> navigate_callbacks;
            std::unique_ptr<CM> plugin_callbacks;

            WindowFunctions(std::shared_ptr<ILogger> logger, RenWeb::App* app);
            ~WindowFunctions();
            WindowFunctions(const WindowFunctions&) = delete;
            WindowFunctions& operator=(const WindowFunctions&) = delete;
            WindowFunctions(WindowFunctions&&) = delete;
            WindowFunctions& operator=(WindowFunctions&&) = delete;
            
            WindowFunctions* bindFunction(const std::string&, std::function<std::string(std::string)>);
            WindowFunctions* unbindFunction(const std::string&);
            json::value get(const std::string& property);
            void set(const std::string& property, const json::value& value);
            json::object getState();
            void setState(const json::object& json);

            WindowFunctions* setup(const json::object& setup_state = json::object{});
            WindowFunctions* teardown();

         // ------------ state -----------------
            bool isFocus();
    };
};