// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#include "../include/app.hpp"

#include "../include/info.hpp"
#include "../include/locate.hpp"
#include "../include/logger.hpp"
#include "../include/managers/process_manager.hpp"
#include "../include/web_server.hpp"
#include "../include/webview.hpp"
#include "../include/interfaces/Iprocess_manager.hpp"
#include "../include/managers/plugin_manager.hpp"
#include <boost/json/array.hpp>
#include <boost/json/object.hpp>
#include <boost/json/value.hpp>

#if defined(_WIN32)
#  define WIN32_LEAN_AND_MEAN
#  include <windows.h>
#elif defined(__APPLE__)
#  import <AppKit/AppKit.h>
#  import <Foundation/Foundation.h>
#elif defined(__linux__) || defined(__CYGWIN__)
#  include <gtk/gtk.h>
#endif

using namespace RenWeb;
using JSON = RenWeb::JSON;

void App::showErrorPopup(const std::string& message) {
#if defined(_WIN32)
    int len = MultiByteToWideChar(CP_UTF8, 0, message.c_str(), -1, nullptr, 0);
    std::wstring wmsg(len, L'\0');
    MultiByteToWideChar(CP_UTF8, 0, message.c_str(), -1, wmsg.data(), len);
    MessageBoxW(nullptr, wmsg.c_str(), L"RenWeb \u2013 Error", MB_OK | MB_ICONERROR);
#elif defined(__APPLE__)
    @autoreleasepool {
        NSString* title = @"RenWeb - Error";
        NSString* msg = [NSString stringWithUTF8String:message.c_str()];
        NSAlert* alert = [[NSAlert alloc] init];
        [alert setAlertStyle:NSAlertStyleCritical];
        [alert setMessageText:title];
        [alert setInformativeText:msg ? msg : @"Unknown error"];
        [alert addButtonWithTitle:@"OK"];
        [alert runModal];
    }
#elif defined(__linux__) || defined(__CYGWIN__)
    if (!gtk_init_check(nullptr, nullptr)) {
        std::fprintf(stderr, "RenWeb - Error: %s\n", message.c_str());
        return;
    }

    GtkWidget* dialog = gtk_message_dialog_new(
        nullptr,
        GTK_DIALOG_MODAL,
        GTK_MESSAGE_ERROR,
        GTK_BUTTONS_OK,
        "%s",
        message.c_str()
    );
    gtk_window_set_title(GTK_WINDOW(dialog), "RenWeb - Error");
    gtk_dialog_run(GTK_DIALOG(dialog));
    gtk_widget_destroy(dialog);

    while (gtk_events_pending()) {
        gtk_main_iteration();
    }
#endif
}

void AppBuilder::validateOpt(const std::string& opt) {
    if (this->opts.find(opt) == this->opts.end()) {
        throw std::runtime_error("[app builder] Option '" + opt + "' missing in opts!");
    }
}

AppBuilder::AppBuilder(
    const std::map<std::string, std::string>& opts, 
    int argc, 
    char** argv)
    : opts(opts), argc(argc), argv(argv)
{ }

AppBuilder& AppBuilder::withLogger(std::shared_ptr<ILogger> logger) {
    this->logger = logger;
    return *this;
}

AppBuilder& AppBuilder::withInfo(std::unique_ptr<JSON> info) {
    this->info = std::move(info);
    return *this;
}

AppBuilder& AppBuilder::withConfig(std::unique_ptr<Config> config) {
    this->config = std::move(config);
    return *this;
}

AppBuilder& AppBuilder::withProcessManager(std::unique_ptr<IProcessManager> procm) {
    this->procm = std::move(procm);
    return *this;
}

AppBuilder& AppBuilder::withWebview(std::unique_ptr<IWebview> w) {
    this->w = std::move(w);
    return *this;
}

AppBuilder& AppBuilder::withWebServer(std::unique_ptr<IWebServer> ws) {
    this->ws = std::move(ws);
    return *this;
}

AppBuilder& AppBuilder::withWindowFunctions(std::unique_ptr<WindowFunctions> fns) {
    this->fns = std::move(fns);
    return *this;
}

AppBuilder& AppBuilder::withPluginManager(std::unique_ptr<PluginManager> pm) {
    this->pm = std::move(pm);
    return *this;
}

std::unique_ptr<App> AppBuilder::build() {      
    if (this->logger == nullptr) {      
        this->withLogger(std::make_unique<Logger>(std::make_unique<LogFlags>(LogFlags{
            .log_silent = opts.at("log_silent") == "true",
            .log_level = static_cast<spdlog::level::level_enum>(std::atoi(opts.at("log_level").c_str())),
            .log_clear = opts.at("log_clear") == "true",
            .log_boring = opts.at("log_boring") == "true"
        })));
        this->validateOpt("page");
        this->logger->refresh({
            {"page", opts.at("page")}
        });
    }

    auto app = std::unique_ptr<App>(new App(this->logger));
    app->orig_args = (argc == 0)
        ? std::vector<std::string>({Locate::executable().string()})
        : std::vector<std::string>(this->argv, this->argv + this->argc);
        
    if (this->info == nullptr) {
        this->withInfo(std::make_unique<JSON>(
            this->logger, 
            Info::getInfoFile())
        );
    }
    app->info = std::move(this->info);
    
    if (this->config == nullptr) {
        this->validateOpt("page");
        this->withConfig(std::make_unique<Config>(
            this->logger,
            opts.at("page")
        ));
    }
    app->config = std::move(this->config);
    
    if (this->w == nullptr) {
        std::string app_id;
        if (app->info) {
            try {
                const auto& jv = app->info->getJson();
                if (jv.is_object()) {
                    const auto& obj = jv.as_object();
                    if (obj.contains("app_id") && obj.at("app_id").is_string())
                        app_id = std::string(obj.at("app_id").as_string());
                }
            } catch (...) {}
        }
        this->withWebview(std::make_unique<RenWeb::Webview>(false, nullptr, app_id, this->logger));
    }
    app->w = std::move(this->w);

    if (this->procm == nullptr) {
        this->withProcessManager(std::make_unique<ProcessManager>(this->logger, app.get()));
    }
    app->procm = std::move(this->procm);

    if (this->ws == nullptr) {
        this->withWebServer(std::make_unique<WebServer>(
            this->logger,
            app.get()
        ));
    }
    app->ws = std::move(this->ws);

    if (this->pm == nullptr) {
        this->withPluginManager(std::make_unique<PluginManager>(
            this->logger
        ));
    }
    app->pm = std::move(this->pm);

    if (this->fns == nullptr) {
        this->withWindowFunctions(std::make_unique<WindowFunctions>(this->logger, app.get()));
    }
    app->fns = std::move(this->fns);  

    return app;
}

void App::run() {
    this->ws->start();
    
    this->procm->registerProcess();
    
    this->w->dispatch([this](){
        json::object current_state = this->config->getJson().is_object() 
            ? this->config->getJson().as_object() : json::object{};
        json::object defaults = this->config->getDefaultsJson().is_object() 
            ? this->config->getDefaultsJson().as_object() : json::object{};

        json::object effective_state;
        if (current_state.empty()) {
            // Page not in config.json (e.g. external URL): use defaults as-is.
            effective_state = defaults;
        } else if (current_state["merge_defaults"] == json::value(true)) {
            effective_state = JSON::merge(defaults, current_state);
        } else {
            effective_state = current_state;
        }
        const bool initially_shown =
            effective_state.contains("initially_shown") &&
            effective_state.at("initially_shown").is_bool()
                ? effective_state.at("initially_shown").as_bool()
                : true;
        if (!initially_shown) {
            this->fns->window_callbacks->run("show", json::array({json::value(false)}));
        }
        this->fns->setState(effective_state);
        this->fns->setup(effective_state);
        this->fns->window_callbacks->run("navigate_page", json::value(this->config->current_page));
    });
    this->w->run();
    this->fns->teardown();
}