// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#include "../include/config.hpp"

#include "../include/file.hpp"
#include "../include/info.hpp"
#include "../include/json.hpp"
#include "../include/locate.hpp"
#include <boost/json/serialize.hpp>
#include <memory>

using Config = RenWeb::Config;
using JSON = RenWeb::JSON;
using File = RenWeb::File;

namespace {
    std::shared_ptr<File> getConfigFile() {
        return std::make_shared<File>(RenWeb::Locate::currentDirectory() / "config.json");
    }
}

Config::Config(
    std::shared_ptr<ILogger> logger,
    const std::string& current_page
) : JSON(logger, getConfigFile()),
    initial_page(current_page),
    current_page(current_page)
{ }

Config::Config(
    std::shared_ptr<ILogger> logger,
    const std::string& current_page,
    std::shared_ptr<File> file
) : JSON(logger, file),
    initial_page(current_page),
    current_page(current_page)
{ }

json::value Config::getProperty(const std::string& key) const /*override*/ {
    try {
        json::value page = JSON::getProperty(this->current_page);
        if (page.is_null()) {
            this->logger->error("[config] Page '" + this->current_page + "' not found in config '" + this->file->getPath().string() + "'. Returning null.");
            return json::value(nullptr);
        }
        return page.at(key);
    } catch (const std::exception& e) {
        this->logger->debug("[config] property '" + key + "' not found in page '" + this->current_page + "': " + std::string(e.what()));
        return json::value(nullptr);
    }
}

json::value Config::getDefaultProperty(const std::string& key) const {
    try {
        json::value defaults = JSON::getProperty(this->DEFAULTS_KEY);
        if (defaults.is_null()) {
            this->logger->error("[config] '__defaults__' section not found in config '" + this->file->getPath().string() + "'. Returning null.");
            return json::value(nullptr);
        }
        return defaults.at(key);
    } catch (const std::exception& e) {
        this->logger->debug("[config] default property '" + key + "' not found in page '" + this->current_page + "': " + std::string(e.what()));
        return json::value(nullptr);
    }
}

void Config::setProperty(const std::string& key, const json::value& value) /*override*/ {
    try {
        json::value page = JSON::getProperty(this->current_page);
        json::object page_obj;
        
        if (page.is_null()) {
            page_obj = {{key, value}};
        } else if (page.is_object()) {
            page_obj = page.as_object();
            page_obj[key] = value;
        } else {
            throw std::runtime_error("[config] Page '" + this->current_page + "' in config '" + this->file->getPath().string() + "' is neither null nor an object (" + json::serialize(page) + ").");
        }
        
        this->json_data.as_object()[this->current_page] = page_obj;
        this->update(this->json_data.as_object());
    } catch (const std::exception& e) {
        this->logger->error("[config] couldn't set property '" + key + "' in page '" + this->current_page + "': " + std::string(e.what()));
    }
}

void Config::setDefaultProperty(const std::string& key, const json::value& value) {
    try {
        json::value defaults = JSON::getProperty(this->DEFAULTS_KEY);
        json::object defaults_obj;
        
        if (defaults.is_null()) {
            defaults_obj = {{key, value}};
        } else if (defaults.is_object()) {
            defaults_obj = defaults.as_object();
            defaults_obj[key] = value;
        } else {
            throw std::runtime_error("[config] Defaults section in config '" + this->file->getPath().string() + "' is neither null nor an object (" + json::serialize(defaults) + ").");
        }
        
        this->json_data.as_object()[this->DEFAULTS_KEY] = defaults_obj;
        this->update(this->json_data.as_object());
    } catch (const std::exception& e) {
        this->logger->error("[config] couldn't set default property '" + key + "' in page '" + this->current_page + "': " + std::string(e.what()));
    }
}


const json::value& Config::getJson() const /*override*/ {
    try {
        if (this->json_data.is_object()) {
            if (this->json_data.as_object().contains(this->current_page)) {
                return this->json_data.as_object().at(this->current_page);
            } else {
                throw std::runtime_error("Current page '" + this->current_page + "' not found in config '" + this->file->getPath().string() + "'.");
            }
        } else {
            throw std::runtime_error("Config is not a JSON object.");
        }
    } catch (const std::exception& e) {
        this->logger->error("[config] An error occurred when getting config.json data:  " + std::string(e.what()));
        static const json::value null_value = nullptr;
        return null_value;
    }
}

const json::value& Config::getDefaultsJson() const /*override*/ {
    try {
        if (this->json_data.is_object()) {
            if (this->json_data.as_object().contains(this->DEFAULTS_KEY)) {
                return this->json_data.as_object().at(this->DEFAULTS_KEY);
            } else {
                throw std::runtime_error("Defaults not found in config '" + this->file->getPath().string() + "'.");
            }
        } else {
            throw std::runtime_error("Config is not a JSON object.");
        }
    } catch (const std::exception& e) {
        this->logger->error("[config] An error occurred when getting config.json data:  " + std::string(e.what()));
        static const json::value null_value = nullptr;
        return null_value;
    }
}


void Config::update(const json::object &new_data) /*override*/ {
    json::object data = new_data;
    if (!data.contains(this->current_page) || !data.at(this->current_page).is_object()) {
        data = {
            {this->current_page, data}
        };
    }
    JSON::update(data);
}