// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#include "../include/file.hpp" 

using File = RenWeb::File;

File::File() 
    : file_path("") 
{ };

File::File(std::filesystem::path file_path) 
    : file_path(std::move(file_path)) 
{ };

const std::filesystem::path File::getName() const {
    return this->file_path.filename();
};

const std::filesystem::path File::getExtension() const {
    return this->file_path.extension();
};

std::filesystem::path File::getDir() const {
    return this->file_path.parent_path();
};

const std::filesystem::path& File::getPath() const {
    return this->file_path;
};

void File::clear() const {
    if (std::filesystem::exists(this->getPath())) {
        std::filesystem::resize_file(this->getPath(), 0);
    }
};

bool File::exists() const {
    return std::filesystem::exists(this->getPath());
};

std::shared_ptr<std::string> File::read() const {
    if (!this->exists()) {
        throw std::runtime_error("File not found at '" + this->getPath().string() + "'. Could not attempt read.");
    }
    std::ifstream file_stream(this->getPath(),  std::ios::in | std::ios::binary);
    auto contents = std::make_shared<std::string>("");
    if (file_stream) {
        file_stream.seekg(0, std::ios::end);
        contents->resize(file_stream.tellg());
        file_stream.seekg(0, std::ios::beg);
        file_stream.read(&(*contents)[0], contents->size());
        file_stream.close();
    } else {
        throw std::runtime_error("Could not open file at '" + this->getPath().string() + "' for reading.");
    }
    return contents;
};

void File::write(const std::string& data) const {
    std::ofstream file_stream(this->getPath(), std::ios::out | std::ios::binary);
    if (file_stream) {
        file_stream.write(data.c_str(), data.size());
        file_stream.close();
    } else {
        throw std::runtime_error("Could not open file at '" + this->getPath().string() + "' for writing.");
    }
};
