// Copyright (C) 2025 spur27
// SPDX-License-Identifier: BSL-1.0
//
// This file is part of RenWeb Engine.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#include "../include/json.hpp"

#include <boost/json/parse.hpp>
#include <memory>
#include <stdexcept>
#include "../include/file.hpp"

using File = RenWeb::File;
using ILogger = RenWeb::ILogger;
using JSON = RenWeb::JSON;
namespace json = boost::json;

JSON::JSON(std::shared_ptr<ILogger> logger, std::shared_ptr<File> file)
    : logger(logger), file(file)
{ 
    if (this->file->exists()) {
        this->json_data = json::parse(this->file->read()->data()).as_object();
    } else {
        this->logger->error("[json] JSON file at '" + this->file->getPath().string() + "' does not exist. Setting to empty object.");
        this->json_data = json::object{};
    }
}

/*static*/ json::value JSON::peek(File* file, const std::string& key) {
    if (file->exists()) {
        try {
            json::object json_contents = json::parse(file->read()->data()).as_object();
            if (json_contents.contains(key)) {
                return json_contents[key];
            } else {
                throw std::runtime_error("[json] Could not find key '" + key + "' when peeking on " + file->getPath().string());
            }
        } catch (...) {
            return json::value(nullptr);
        }
    } else {
        throw std::runtime_error("[json] File does not exist: " + file->getPath().string());
    }
}

/*static*/ json::object JSON::merge(json::object old_data, const json::object& new_data) {
    for (const auto& [key, val] : new_data) {
        if (val.is_object() && old_data.contains(key) && old_data.at(key).is_object()) {
            old_data[key] = JSON::merge(old_data.at(key).get_object(), val.get_object());
        } else {
            old_data[key] = val;
        }
    }
    return old_data;
}

/*virtual*/ const json::value& JSON::getJson() const {
    return this->json_data;
}


/*virtual*/ json::value JSON::getProperty(const std::string& key) const {
    try {
        if (this->json_data.as_object().contains(key)) {
            return this->json_data.as_object().at(key);
        } else {
            this->logger->debug("[json] property '" + key + "' not found");
        }
    } catch (const std::exception& e) {
        this->logger->error("[json] " + std::string(e.what()));
    }
    return json::value(nullptr);
}

/*virtual*/ void JSON::setProperty(const std::string& key, const json::value& value) {
    try {
        this->json_data.as_object()[key] = value;
    } catch (const std::exception& e) {
        this->logger->error("[json] couldn't set property '" + key + "': " + std::string(e.what()));
    }
}

/*virtual*/ void JSON::update(const json::object& new_data) {
    try {
        json::value file_data = json::parse((this->file->exists()) ? this->file->read()->data() : "{}");
        if (!file_data.is_object()) file_data = json::object();
        this->json_data = JSON::merge(
            JSON::merge(file_data.as_object(), this->json_data.as_object()),
            new_data
        );
        std::string formatted = json::serialize(this->json_data);

        std::string pretty;
        int indent = 0;
        bool in_string = false;
        for (size_t i = 0; i < formatted.size(); ++i) {
            char c = formatted[i];
            if (c == '"' && (i == 0 || formatted[i-1] != '\\')) in_string = !in_string;
            if (!in_string) {
                if (c == '{' || c == '[') {
                    pretty += c;
                    pretty += '\n';
                    pretty += std::string(++indent * 2, ' ');
                } else if (c == '}' || c == ']') {
                    pretty += '\n';
                    pretty += std::string(--indent * 2, ' ');
                    pretty += c;
                } else if (c == ',') {
                    pretty += c;
                    pretty += '\n';
                    pretty += std::string(indent * 2, ' ');
                } else if (c == ':') {
                    pretty += c;
                    pretty += ' ';
                } else if (c != ' ') {
                    pretty += c;
                }
            } else {
                pretty += c;
            }
        }
        this->file->write(pretty);
    } catch (const std::exception& e) {
        this->logger->error("[json] couldn't update json: " + std::string(e.what()));
        this->file->write(json::serialize(this->json_data));
    }
}
